//go:build !test && !js

package main

import (
	"strconv"
	"strings"

	"github.com/ingyamilmolinar/beatmo/internal/audio"
)

// generate returns the full text of src/js/modular_instruments.gen.js for the
// given table. Kept separate from main() so it is a single pure function; the
// drift test re-runs the generator via `go run` and diffs the on-disk file.
func generate(defs []audio.ModularInstrumentDef) string {
	var b strings.Builder

	b.WriteString("// Code generated by cmd/gen-modular-instruments. DO NOT EDIT.\n")
	b.WriteString("//\n")
	b.WriteString("// Source of truth: src/go/internal/audio/modular_instruments.go\n")
	b.WriteString("// Regenerate: cd src/go && go run ./cmd/gen-modular-instruments > ../js/modular_instruments.gen.js\n")
	b.WriteString("\n")

	b.WriteString("// MODULAR_RENDER maps each config-table modular instrument id to its render\n")
	b.WriteString("// function. audio.js Object.assign()s this into the RENDER table so browser\n")
	b.WriteString("// playback resolves the instrument (audio.js throws \"Unknown sound\" for an id\n")
	b.WriteString("// absent from RENDER). Deterministic order = modularInstrumentDefs table order.\n")
	b.WriteString("export const MODULAR_RENDER = Object.freeze({\n")
	for _, d := range defs {
		b.WriteString("  " + jsKey(d.ID) + ": 'render_modular',\n")
	}
	b.WriteString("});\n\n")

	b.WriteString("// MODULAR_RENDER_INFO carries each instrument's WASM one-shot render duration\n")
	b.WriteString("// (seconds), playback amplitude (amp) and param block. Object.assign()d into\n")
	b.WriteString("// RENDER_INFO. paramBlock is always 'modular' — every table instrument is a\n")
	b.WriteString("// seed over the modular voice.\n")
	b.WriteString("export const MODULAR_RENDER_INFO = Object.freeze({\n")
	for _, d := range defs {
		b.WriteString("  " + jsKey(d.ID) + ": { seconds: " + formatF64(d.DurationSec) +
			", amp: " + formatF32(d.Amplitude) + ", paramBlock: 'modular' },\n")
	}
	b.WriteString("});\n")

	return b.String()
}

// jsKey renders an instrument id as a single-quoted JS object key, matching the
// existing audio.js RENDER/RENDER_INFO style (every modular id contains a
// hyphen, so quoting is required anyway).
func jsKey(id string) string {
	return "'" + strings.ReplaceAll(id, "'", `\'`) + "'"
}

// formatF64 renders a float64 with the shortest exact decimal (e.g. 0.5, 0.75).
func formatF64(v float64) string {
	return strconv.FormatFloat(v, 'g', -1, 64)
}

// formatF32 renders a float32 with the shortest exact decimal at 32-bit
// precision so 0.8 does not expand to 0.800000011920929.
func formatF32(v float32) string {
	return strconv.FormatFloat(float64(v), 'g', -1, 32)
}
