// Code generated by cmd/gen_design_tokens. DO NOT EDIT.
//
// Source of truth: DESIGN.md `densities:` block.
// Regenerate via: make gen-design-tokens

package ui

// densityValues is the generated container for density-conditional
// design fields. density_profile.go's densityValuesFor() returns
// the right variable for the active Density. Fields here are the
// "size of interactive controls" subset of dimensional design tokens
// — selected for being density-tied (finger-vs-mouse), not
// screen-class-tied (viewport-narrow-vs-wide).
type densityValues struct {
	AccentStripeInsetY     int // densities.accentStripeInsetY
	AccentStripeWidth      int // densities.accentStripeWidth
	AudioChannelMinW       int // densities.audioChannelMinW
	AudioLabelMarginW      int // densities.audioLabelMarginW
	AudioPillGap           int // densities.audioPillGap
	AudioPillH             int // densities.audioPillH
	AudioPillNarrowW       int // densities.audioPillNarrowW
	AudioPillPadX          int // densities.audioPillPadX
	AudioTabMinW           int // densities.audioTabMinW
	ChainAutoFitMinMs      int // densities.chainAutoFitMinMs
	ChainBadgeScale        int // densities.chainBadgeScale
	ChainContentGap        int // densities.chainContentGap
	ChainLabelScale        int // densities.chainLabelScale
	ChainLegendStripH      int // densities.chainLegendStripH
	ChainMiniMeterGap      int // densities.chainMiniMeterGap
	ChainMiniMeterW        int // densities.chainMiniMeterW
	ChainMiniWaveH         int // densities.chainMiniWaveH
	ChainPillScale         int // densities.chainPillScale
	ChainReadoutScale      int // densities.chainReadoutScale
	ChainScopeBottomMargin int // densities.chainScopeBottomMargin
	ChainScopeLeftMargin   int // densities.chainScopeLeftMargin
	ChainStageColW         int // densities.chainStageColW
	ChainStageRowH         int // densities.chainStageRowH
	ChainTriggerMarkerW    int // densities.chainTriggerMarkerW
	CloseButtonSize        int // densities.closeButtonSize
	ControlGap             int // densities.controlGap
	ControlGroupPad        int // densities.controlGroupPad
	ControlPadding         int // densities.controlPadding
	EdgeThickMul           int // densities.edgeThickMul
	EqDBInputH             int // densities.eqDBInputH
	EqHandleRadius         int // densities.eqHandleRadius
	EqSliderH              int // densities.eqSliderH
	FxToggleThumbD         int // densities.fxToggleThumbD
	FxToggleTrackH         int // densities.fxToggleTrackH
	FxToggleTrackW         int // densities.fxToggleTrackW
	GrabZone               int // densities.grabZone
	HeaderMaxH             int // densities.headerMaxH
	HeaderMinH             int // densities.headerMinH
	KnobStepBadgeH         int // densities.knobStepBadgeH
	KnobStepBadgeW         int // densities.knobStepBadgeW
	LevelsReadoutFooterH   int // densities.levelsReadoutFooterH
	LevelsReadoutWFull     int // densities.levelsReadoutWFull
	LevelsReadoutWIcons    int // densities.levelsReadoutWIcons
	MinTarget              int // densities.minTarget
	MobileWheelH           int // densities.mobileWheelH
	MobileWheelPillH       int // densities.mobileWheelPillH
	MobileWheelResStripW   int // densities.mobileWheelResStripW
	MobileWheelTickGap     int // densities.mobileWheelTickGap
	MobileWheelW           int // densities.mobileWheelW
	NodeMaxPx              int // densities.nodeMaxPx
	NodeMinPx              int // densities.nodeMinPx
	PopupBtnH              int // densities.popupBtnH
	PopupBtnW              int // densities.popupBtnW
	PopupGap               int // densities.popupGap
	PopupPad               int // densities.popupPad
	PopupSectionGap        int // densities.popupSectionGap
	RowControlBtnSize      int // densities.rowControlBtnSize
	RowHeight              int // densities.rowHeight
	SamplerMinBodyH        int // densities.samplerMinBodyH
	SamplerPlayheadStroke  int // densities.samplerPlayheadStroke
	SamplerWaveMinH        int // densities.samplerWaveMinH
	SidebarLabelScale      int // densities.sidebarLabelScale
	SidebarValuePillW      int // densities.sidebarValuePillW
	SliderThumbH           int // densities.sliderThumbH
	SliderThumbW           int // densities.sliderThumbW
	SliderTrackH           int // densities.sliderTrackH
	SpectrumBracketH       int // densities.spectrumBracketH
	SpectrumCursorStroke   int // densities.spectrumCursorStroke
	SplitterGrabThreshold  int // densities.splitterGrabThreshold
	SplitterHandleLen      int // densities.splitterHandleLen
	SplitterHandleThk      int // densities.splitterHandleThk
	SynthChipH             int // densities.synthChipH
	SynthChipMinW          int // densities.synthChipMinW
	SynthChipStripH        int // densities.synthChipStripH
	SynthConceptVizH       int // densities.synthConceptVizH
	SynthDetailHeaderH     int // densities.synthDetailHeaderH
	SynthFocusGraphH       int // densities.synthFocusGraphH
	SynthHeaderButtonH     int // densities.synthHeaderButtonH
	SynthHeaderThumbW      int // densities.synthHeaderThumbW
	SynthKnobCaptionH      int // densities.synthKnobCaptionH
	SynthKnobIdeal         int // densities.synthKnobIdeal
	SynthKnobMin           int // densities.synthKnobMin
	SynthPreviewMinW       int // densities.synthPreviewMinW
	SynthPreviewTargetW    int // densities.synthPreviewTargetW
	SynthRightCardMinH     int // densities.synthRightCardMinH
	SynthSectionMinH       int // densities.synthSectionMinH
	TimelineBarH           int // densities.timelineBarH
	TransportBtnSize       int // densities.transportBtnSize
	WaveCursorStroke       int // densities.waveCursorStroke
}

var (
	genComfortableDensity = densityValues{
		AccentStripeInsetY:     0,
		AccentStripeWidth:      3,
		AudioChannelMinW:       72,
		AudioLabelMarginW:      28,
		AudioPillGap:           3,
		AudioPillH:             24,
		AudioPillNarrowW:       18,
		AudioPillPadX:          16,
		AudioTabMinW:           28,
		ChainAutoFitMinMs:      2,
		ChainBadgeScale:        900,
		ChainContentGap:        8,
		ChainLabelScale:        850,
		ChainLegendStripH:      16,
		ChainMiniMeterGap:      3,
		ChainMiniMeterW:        6,
		ChainMiniWaveH:         7,
		ChainPillScale:         850,
		ChainReadoutScale:      800,
		ChainScopeBottomMargin: 18,
		ChainScopeLeftMargin:   34,
		ChainStageColW:         64,
		ChainStageRowH:         26,
		ChainTriggerMarkerW:    3,
		CloseButtonSize:        22,
		ControlGap:             2,
		ControlGroupPad:        3,
		ControlPadding:         4,
		EdgeThickMul:           1,
		EqDBInputH:             14,
		EqHandleRadius:         16,
		EqSliderH:              14,
		FxToggleThumbD:         14,
		FxToggleTrackH:         18,
		FxToggleTrackW:         32,
		GrabZone:               5,
		HeaderMaxH:             40,
		HeaderMinH:             40,
		KnobStepBadgeH:         18,
		KnobStepBadgeW:         44,
		LevelsReadoutFooterH:   16,
		LevelsReadoutWFull:     180,
		LevelsReadoutWIcons:    36,
		MinTarget:              0,
		MobileWheelH:           300,
		MobileWheelPillH:       38,
		MobileWheelResStripW:   40,
		MobileWheelTickGap:     34,
		MobileWheelW:           220,
		NodeMaxPx:              16,
		NodeMinPx:              8,
		PopupBtnH:              16,
		PopupBtnW:              18,
		PopupGap:               4,
		PopupPad:               6,
		PopupSectionGap:        4,
		RowControlBtnSize:      28,
		RowHeight:              36,
		SamplerMinBodyH:        48,
		SamplerPlayheadStroke:  4,
		SamplerWaveMinH:        36,
		SidebarLabelScale:      1200,
		SidebarValuePillW:      50,
		SliderThumbH:           18,
		SliderThumbW:           12,
		SliderTrackH:           4,
		SpectrumBracketH:       12,
		SpectrumCursorStroke:   1,
		SplitterGrabThreshold:  0,
		SplitterHandleLen:      50,
		SplitterHandleThk:      8,
		SynthChipH:             26,
		SynthChipMinW:          64,
		SynthChipStripH:        34,
		SynthConceptVizH:       50,
		SynthDetailHeaderH:     34,
		SynthFocusGraphH:       120,
		SynthHeaderButtonH:     28,
		SynthHeaderThumbW:      120,
		SynthKnobCaptionH:      18,
		SynthKnobIdeal:         72,
		SynthKnobMin:           28,
		SynthPreviewMinW:       160,
		SynthPreviewTargetW:    280,
		SynthRightCardMinH:     40,
		SynthSectionMinH:       72,
		TimelineBarH:           12,
		TransportBtnSize:       32,
		WaveCursorStroke:       1,
	}
	genCompactDensity = densityValues{
		AccentStripeInsetY:     0,
		AccentStripeWidth:      2,
		AudioChannelMinW:       60,
		AudioLabelMarginW:      24,
		AudioPillGap:           2,
		AudioPillH:             20,
		AudioPillNarrowW:       16,
		AudioPillPadX:          12,
		AudioTabMinW:           24,
		ChainAutoFitMinMs:      2,
		ChainBadgeScale:        800,
		ChainContentGap:        6,
		ChainLabelScale:        800,
		ChainLegendStripH:      14,
		ChainMiniMeterGap:      2,
		ChainMiniMeterW:        3,
		ChainMiniWaveH:         5,
		ChainPillScale:         800,
		ChainReadoutScale:      750,
		ChainScopeBottomMargin: 14,
		ChainScopeLeftMargin:   28,
		ChainStageColW:         48,
		ChainStageRowH:         20,
		ChainTriggerMarkerW:    2,
		CloseButtonSize:        20,
		ControlGap:             2,
		ControlGroupPad:        2,
		ControlPadding:         3,
		EdgeThickMul:           1,
		EqDBInputH:             12,
		EqHandleRadius:         14,
		EqSliderH:              12,
		FxToggleThumbD:         12,
		FxToggleTrackH:         14,
		FxToggleTrackW:         28,
		GrabZone:               4,
		HeaderMaxH:             36,
		HeaderMinH:             36,
		KnobStepBadgeH:         16,
		KnobStepBadgeW:         38,
		LevelsReadoutFooterH:   14,
		LevelsReadoutWFull:     120,
		LevelsReadoutWIcons:    28,
		MinTarget:              0,
		MobileWheelH:           260,
		MobileWheelPillH:       34,
		MobileWheelResStripW:   36,
		MobileWheelTickGap:     30,
		MobileWheelW:           200,
		NodeMaxPx:              14,
		NodeMinPx:              6,
		PopupBtnH:              14,
		PopupBtnW:              16,
		PopupGap:               3,
		PopupPad:               4,
		PopupSectionGap:        3,
		RowControlBtnSize:      24,
		RowHeight:              32,
		SamplerMinBodyH:        42,
		SamplerPlayheadStroke:  3,
		SamplerWaveMinH:        30,
		SidebarLabelScale:      1100,
		SidebarValuePillW:      44,
		SliderThumbH:           16,
		SliderThumbW:           10,
		SliderTrackH:           3,
		SpectrumBracketH:       8,
		SpectrumCursorStroke:   1,
		SplitterGrabThreshold:  0,
		SplitterHandleLen:      44,
		SplitterHandleThk:      7,
		SynthChipH:             22,
		SynthChipMinW:          56,
		SynthChipStripH:        28,
		SynthConceptVizH:       38,
		SynthDetailHeaderH:     28,
		SynthFocusGraphH:       96,
		SynthHeaderButtonH:     24,
		SynthHeaderThumbW:      96,
		SynthKnobCaptionH:      14,
		SynthKnobIdeal:         56,
		SynthKnobMin:           24,
		SynthPreviewMinW:       140,
		SynthPreviewTargetW:    240,
		SynthRightCardMinH:     34,
		SynthSectionMinH:       56,
		TimelineBarH:           10,
		TransportBtnSize:       28,
		WaveCursorStroke:       1,
	}
	genSpaciousDensity = densityValues{
		AccentStripeInsetY:     2,
		AccentStripeWidth:      5,
		AudioChannelMinW:       84,
		AudioLabelMarginW:      32,
		AudioPillGap:           4,
		AudioPillH:             30,
		AudioPillNarrowW:       22,
		AudioPillPadX:          20,
		AudioTabMinW:           34,
		ChainAutoFitMinMs:      2,
		ChainBadgeScale:        1050,
		ChainContentGap:        10,
		ChainLabelScale:        1100,
		ChainLegendStripH:      22,
		ChainMiniMeterGap:      4,
		ChainMiniMeterW:        10,
		ChainMiniWaveH:         12,
		ChainPillScale:         1050,
		ChainReadoutScale:      1000,
		ChainScopeBottomMargin: 26,
		ChainScopeLeftMargin:   48,
		ChainStageColW:         72,
		ChainStageRowH:         36,
		ChainTriggerMarkerW:    4,
		CloseButtonSize:        28,
		ControlGap:             4,
		ControlGroupPad:        4,
		ControlPadding:         4,
		EdgeThickMul:           2,
		EqDBInputH:             20,
		EqHandleRadius:         26,
		EqSliderH:              28,
		FxToggleThumbD:         18,
		FxToggleTrackH:         22,
		FxToggleTrackW:         40,
		GrabZone:               16,
		HeaderMaxH:             56,
		HeaderMinH:             56,
		KnobStepBadgeH:         22,
		KnobStepBadgeW:         52,
		LevelsReadoutFooterH:   20,
		LevelsReadoutWFull:     220,
		LevelsReadoutWIcons:    34,
		MinTarget:              44,
		MobileWheelH:           340,
		MobileWheelPillH:       44,
		MobileWheelResStripW:   44,
		MobileWheelTickGap:     38,
		MobileWheelW:           240,
		NodeMaxPx:              20,
		NodeMinPx:              12,
		PopupBtnH:              36,
		PopupBtnW:              44,
		PopupGap:               6,
		PopupPad:               10,
		PopupSectionGap:        8,
		RowControlBtnSize:      36,
		RowHeight:              44,
		SamplerMinBodyH:        56,
		SamplerPlayheadStroke:  5,
		SamplerWaveMinH:        44,
		SidebarLabelScale:      1300,
		SidebarValuePillW:      56,
		SliderThumbH:           24,
		SliderThumbW:           14,
		SliderTrackH:           6,
		SpectrumBracketH:       16,
		SpectrumCursorStroke:   3,
		SplitterGrabThreshold:  8,
		SplitterHandleLen:      56,
		SplitterHandleThk:      6,
		SynthChipH:             32,
		SynthChipMinW:          72,
		SynthChipStripH:        40,
		SynthConceptVizH:       58,
		SynthDetailHeaderH:     44,
		SynthFocusGraphH:       140,
		SynthHeaderButtonH:     44,
		SynthHeaderThumbW:      80,
		SynthKnobCaptionH:      22,
		SynthKnobIdeal:         88,
		SynthKnobMin:           40,
		SynthPreviewMinW:       180,
		SynthPreviewTargetW:    320,
		SynthRightCardMinH:     44,
		SynthSectionMinH:       96,
		TimelineBarH:           14,
		TransportBtnSize:       44,
		WaveCursorStroke:       3,
	}
)
