// Code generated by cmd/gen_design_tokens. DO NOT EDIT.
//
// Source of truth: DESIGN.md `densities:` block.
// Regenerate via: make gen-design-tokens

package ui

// densityValues is the generated container for density-conditional
// design fields. density_profile.go's densityValuesFor() returns
// the right variable for the active Density. Fields here are the
// "size of interactive controls" subset of dimensional design tokens
// — selected for being density-tied (finger-vs-mouse), not
// screen-class-tied (viewport-narrow-vs-wide).
type densityValues struct {
	AccentStripeInsetY     int // densities.accentStripeInsetY
	AccentStripeWidth      int // densities.accentStripeWidth
	ChainAggregateH        int // densities.chainAggregateH
	ChainAggregateW        int // densities.chainAggregateW
	ChainAutoFitMinMs      int // densities.chainAutoFitMinMs
	ChainBadgeScale        int // densities.chainBadgeScale
	ChainLabelScale        int // densities.chainLabelScale
	ChainLegendStripH      int // densities.chainLegendStripH
	ChainMiniMeterGap      int // densities.chainMiniMeterGap
	ChainMiniMeterW        int // densities.chainMiniMeterW
	ChainMiniWaveH         int // densities.chainMiniWaveH
	ChainModePillW         int // densities.chainModePillW
	ChainPillScale         int // densities.chainPillScale
	ChainReadoutScale      int // densities.chainReadoutScale
	ChainScopeBottomMargin int // densities.chainScopeBottomMargin
	ChainScopeLeftMargin   int // densities.chainScopeLeftMargin
	ChainStageColW         int // densities.chainStageColW
	ChainStageRowH         int // densities.chainStageRowH
	ChainTriggerMarkerW    int // densities.chainTriggerMarkerW
	CloseButtonSize        int // densities.closeButtonSize
	ControlGap             int // densities.controlGap
	ControlGroupPad        int // densities.controlGroupPad
	ControlPadding         int // densities.controlPadding
	EdgeThickMul           int // densities.edgeThickMul
	EqDBInputH             int // densities.eqDBInputH
	EqHandleRadius         int // densities.eqHandleRadius
	EqSliderH              int // densities.eqSliderH
	FxToggleThumbD         int // densities.fxToggleThumbD
	FxToggleTrackH         int // densities.fxToggleTrackH
	FxToggleTrackW         int // densities.fxToggleTrackW
	GrabZone               int // densities.grabZone
	HeaderMaxH             int // densities.headerMaxH
	HeaderMinH             int // densities.headerMinH
	LevelsReadoutFooterH   int // densities.levelsReadoutFooterH
	LevelsReadoutWFull     int // densities.levelsReadoutWFull
	LevelsReadoutWIcons    int // densities.levelsReadoutWIcons
	MinTarget              int // densities.minTarget
	NodeMaxPx              int // densities.nodeMaxPx
	NodeMinPx              int // densities.nodeMinPx
	PopupBtnH              int // densities.popupBtnH
	PopupBtnW              int // densities.popupBtnW
	PopupGap               int // densities.popupGap
	PopupPad               int // densities.popupPad
	PopupSectionGap        int // densities.popupSectionGap
	RowControlBtnSize      int // densities.rowControlBtnSize
	RowHeight              int // densities.rowHeight
	SamplerPlayheadStroke  int // densities.samplerPlayheadStroke
	SliderThumbH           int // densities.sliderThumbH
	SliderThumbW           int // densities.sliderThumbW
	SliderTrackH           int // densities.sliderTrackH
	SpectrumBracketH       int // densities.spectrumBracketH
	SpectrumCursorStroke   int // densities.spectrumCursorStroke
	SplitterGrabThreshold  int // densities.splitterGrabThreshold
	SplitterHandleLen      int // densities.splitterHandleLen
	SplitterHandleThk      int // densities.splitterHandleThk
	SynthChipH             int // densities.synthChipH
	SynthChipMinW          int // densities.synthChipMinW
	SynthChipStripH        int // densities.synthChipStripH
	SynthDetailHeaderH     int // densities.synthDetailHeaderH
	SynthHeaderButtonH     int // densities.synthHeaderButtonH
	SynthHeaderThumbW      int // densities.synthHeaderThumbW
	SynthKnobCaptionH      int // densities.synthKnobCaptionH
	SynthKnobIdeal         int // densities.synthKnobIdeal
	SynthKnobMin           int // densities.synthKnobMin
	SynthSectionMinH       int // densities.synthSectionMinH
	TimelineBarH           int // densities.timelineBarH
	TransportBtnSize       int // densities.transportBtnSize
	WaveCursorStroke       int // densities.waveCursorStroke
}

var (
	genComfortableDensity = densityValues{
		AccentStripeInsetY:     0,
		AccentStripeWidth:      3,
		ChainAggregateH:        16,
		ChainAggregateW:        26,
		ChainAutoFitMinMs:      2,
		ChainBadgeScale:        900,
		ChainLabelScale:        850,
		ChainLegendStripH:      16,
		ChainMiniMeterGap:      3,
		ChainMiniMeterW:        6,
		ChainMiniWaveH:         7,
		ChainModePillW:         36,
		ChainPillScale:         850,
		ChainReadoutScale:      800,
		ChainScopeBottomMargin: 18,
		ChainScopeLeftMargin:   34,
		ChainStageColW:         64,
		ChainStageRowH:         26,
		ChainTriggerMarkerW:    3,
		CloseButtonSize:        16,
		ControlGap:             2,
		ControlGroupPad:        3,
		ControlPadding:         4,
		EdgeThickMul:           1,
		EqDBInputH:             14,
		EqHandleRadius:         16,
		EqSliderH:              14,
		FxToggleThumbD:         14,
		FxToggleTrackH:         18,
		FxToggleTrackW:         32,
		GrabZone:               5,
		HeaderMaxH:             40,
		HeaderMinH:             40,
		LevelsReadoutFooterH:   16,
		LevelsReadoutWFull:     180,
		LevelsReadoutWIcons:    36,
		MinTarget:              0,
		NodeMaxPx:              16,
		NodeMinPx:              8,
		PopupBtnH:              16,
		PopupBtnW:              18,
		PopupGap:               4,
		PopupPad:               6,
		PopupSectionGap:        4,
		RowControlBtnSize:      28,
		RowHeight:              36,
		SamplerPlayheadStroke:  4,
		SliderThumbH:           18,
		SliderThumbW:           12,
		SliderTrackH:           4,
		SpectrumBracketH:       12,
		SpectrumCursorStroke:   1,
		SplitterGrabThreshold:  0,
		SplitterHandleLen:      50,
		SplitterHandleThk:      8,
		SynthChipH:             26,
		SynthChipMinW:          64,
		SynthChipStripH:        34,
		SynthDetailHeaderH:     34,
		SynthHeaderButtonH:     28,
		SynthHeaderThumbW:      120,
		SynthKnobCaptionH:      18,
		SynthKnobIdeal:         72,
		SynthKnobMin:           28,
		SynthSectionMinH:       72,
		TimelineBarH:           12,
		TransportBtnSize:       32,
		WaveCursorStroke:       1,
	}
	genCompactDensity = densityValues{
		AccentStripeInsetY:     0,
		AccentStripeWidth:      2,
		ChainAggregateH:        14,
		ChainAggregateW:        22,
		ChainAutoFitMinMs:      2,
		ChainBadgeScale:        800,
		ChainLabelScale:        800,
		ChainLegendStripH:      14,
		ChainMiniMeterGap:      2,
		ChainMiniMeterW:        3,
		ChainMiniWaveH:         5,
		ChainModePillW:         28,
		ChainPillScale:         800,
		ChainReadoutScale:      750,
		ChainScopeBottomMargin: 14,
		ChainScopeLeftMargin:   28,
		ChainStageColW:         48,
		ChainStageRowH:         20,
		ChainTriggerMarkerW:    2,
		CloseButtonSize:        14,
		ControlGap:             2,
		ControlGroupPad:        2,
		ControlPadding:         3,
		EdgeThickMul:           1,
		EqDBInputH:             12,
		EqHandleRadius:         14,
		EqSliderH:              12,
		FxToggleThumbD:         12,
		FxToggleTrackH:         14,
		FxToggleTrackW:         28,
		GrabZone:               4,
		HeaderMaxH:             36,
		HeaderMinH:             36,
		LevelsReadoutFooterH:   14,
		LevelsReadoutWFull:     120,
		LevelsReadoutWIcons:    28,
		MinTarget:              0,
		NodeMaxPx:              14,
		NodeMinPx:              6,
		PopupBtnH:              14,
		PopupBtnW:              16,
		PopupGap:               3,
		PopupPad:               4,
		PopupSectionGap:        3,
		RowControlBtnSize:      24,
		RowHeight:              32,
		SamplerPlayheadStroke:  3,
		SliderThumbH:           16,
		SliderThumbW:           10,
		SliderTrackH:           3,
		SpectrumBracketH:       8,
		SpectrumCursorStroke:   1,
		SplitterGrabThreshold:  0,
		SplitterHandleLen:      44,
		SplitterHandleThk:      7,
		SynthChipH:             22,
		SynthChipMinW:          56,
		SynthChipStripH:        28,
		SynthDetailHeaderH:     28,
		SynthHeaderButtonH:     24,
		SynthHeaderThumbW:      96,
		SynthKnobCaptionH:      14,
		SynthKnobIdeal:         56,
		SynthKnobMin:           24,
		SynthSectionMinH:       56,
		TimelineBarH:           10,
		TransportBtnSize:       28,
		WaveCursorStroke:       1,
	}
	genSpaciousDensity = densityValues{
		AccentStripeInsetY:     2,
		AccentStripeWidth:      5,
		ChainAggregateH:        20,
		ChainAggregateW:        32,
		ChainAutoFitMinMs:      2,
		ChainBadgeScale:        1050,
		ChainLabelScale:        1100,
		ChainLegendStripH:      22,
		ChainMiniMeterGap:      4,
		ChainMiniMeterW:        10,
		ChainMiniWaveH:         12,
		ChainModePillW:         48,
		ChainPillScale:         1050,
		ChainReadoutScale:      1000,
		ChainScopeBottomMargin: 26,
		ChainScopeLeftMargin:   48,
		ChainStageColW:         72,
		ChainStageRowH:         36,
		ChainTriggerMarkerW:    4,
		CloseButtonSize:        28,
		ControlGap:             4,
		ControlGroupPad:        4,
		ControlPadding:         4,
		EdgeThickMul:           2,
		EqDBInputH:             20,
		EqHandleRadius:         26,
		EqSliderH:              28,
		FxToggleThumbD:         18,
		FxToggleTrackH:         22,
		FxToggleTrackW:         40,
		GrabZone:               16,
		HeaderMaxH:             56,
		HeaderMinH:             56,
		LevelsReadoutFooterH:   20,
		LevelsReadoutWFull:     220,
		LevelsReadoutWIcons:    44,
		MinTarget:              44,
		NodeMaxPx:              20,
		NodeMinPx:              12,
		PopupBtnH:              36,
		PopupBtnW:              44,
		PopupGap:               6,
		PopupPad:               10,
		PopupSectionGap:        8,
		RowControlBtnSize:      32,
		RowHeight:              44,
		SamplerPlayheadStroke:  5,
		SliderThumbH:           24,
		SliderThumbW:           14,
		SliderTrackH:           6,
		SpectrumBracketH:       16,
		SpectrumCursorStroke:   3,
		SplitterGrabThreshold:  8,
		SplitterHandleLen:      56,
		SplitterHandleThk:      6,
		SynthChipH:             32,
		SynthChipMinW:          72,
		SynthChipStripH:        40,
		SynthDetailHeaderH:     44,
		SynthHeaderButtonH:     44,
		SynthHeaderThumbW:      80,
		SynthKnobCaptionH:      22,
		SynthKnobIdeal:         88,
		SynthKnobMin:           40,
		SynthSectionMinH:       96,
		TimelineBarH:           14,
		TransportBtnSize:       44,
		WaveCursorStroke:       3,
	}
)
