// Code generated by cmd/gen_design_tokens. DO NOT EDIT.
//
// Source of truth: DESIGN.md (YAML front matter).
// Regenerate via: make gen-design-tokens

package ui

import "image/color"

// ── Colors ─────────────────────────────────────────────────────────────────
//
// One variable per entry under DESIGN.md `colors:`. Alpha is always
// 255 here (Stitch only allows opaque #RRGGBB); semi-transparent uses
// compose these via WithAlpha() + a named bucket below.
var (
	genColorPrimary                     = color.RGBA{255, 140, 90, 255}  // colors.primary = #FF8C5A
	genColorPrimaryBright               = color.RGBA{255, 180, 152, 255} // colors.primary-bright = #FFB498
	genColorPrimaryDim                  = color.RGBA{197, 100, 72, 255}  // colors.primary-dim = #C56448
	genColorBackground                  = color.RGBA{16, 20, 28, 255}    // colors.background = #10141C
	genColorSurface1                    = color.RGBA{26, 31, 44, 255}    // colors.surface-1 = #1A1F2C
	genColorSurface2                    = color.RGBA{38, 44, 60, 255}    // colors.surface-2 = #262C3C
	genColorSurface3                    = color.RGBA{52, 59, 78, 255}    // colors.surface-3 = #343B4E
	genColorSurfaceOverlay              = color.RGBA{31, 37, 51, 255}    // colors.surface-overlay = #1F2533
	genColorOnSurface                   = color.RGBA{252, 239, 208, 255} // colors.on-surface = #FCEFD0
	genColorOnSurfaceMuted              = color.RGBA{160, 176, 200, 255} // colors.on-surface-muted = #A0B0C8
	genColorOnSurfaceDisabled           = color.RGBA{90, 100, 112, 255}  // colors.on-surface-disabled = #5A6470
	genColorOnSurfaceAccent             = color.RGBA{255, 140, 90, 255}  // colors.on-surface-accent = #FF8C5A
	genColorBorder                      = color.RGBA{255, 255, 255, 255} // colors.border = #FFFFFF
	genColorSuccess                     = color.RGBA{80, 208, 128, 255}  // colors.success = #50D080
	genColorError                       = color.RGBA{255, 88, 72, 255}   // colors.error = #FF5848
	genColorMute                        = color.RGBA{160, 72, 48, 255}   // colors.mute = #A04830
	genColorDestructive                 = color.RGBA{72, 20, 20, 255}    // colors.destructive = #481414
	genColorDestructiveBorder           = color.RGBA{160, 56, 48, 255}   // colors.destructive-border = #A03830
	genColorRecordIdle                  = color.RGBA{224, 64, 64, 255}   // colors.record-idle = #E04040
	genColorRecordActive                = color.RGBA{255, 64, 64, 255}   // colors.record-active = #FF4040
	genColorVizBg                       = color.RGBA{19, 23, 31, 255}    // colors.viz-bg = #13171F
	genColorVizBar                      = color.RGBA{90, 200, 224, 255}  // colors.viz-bar = #5AC8E0
	genColorVizBarPeak                  = color.RGBA{160, 224, 255, 255} // colors.viz-bar-peak = #A0E0FF
	genColorVizCurve                    = color.RGBA{255, 140, 90, 255}  // colors.viz-curve = #FF8C5A
	genColorVizWaveA                    = color.RGBA{128, 224, 255, 255} // colors.viz-wave-a = #80E0FF
	genColorVizWaveB                    = color.RGBA{122, 138, 168, 255} // colors.viz-wave-b = #7A8AA8
	genColorVizMeterGreen               = color.RGBA{80, 208, 128, 255}  // colors.viz-meter-green = #50D080
	genColorVizMeterYellow              = color.RGBA{240, 224, 32, 255}  // colors.viz-meter-yellow = #F0E020
	genColorVizMeterRed                 = color.RGBA{255, 64, 48, 255}   // colors.viz-meter-red = #FF4030
	genColorVizMeterBg                  = color.RGBA{26, 36, 56, 255}    // colors.viz-meter-bg = #1A2438
	genColorVizMeterClip                = color.RGBA{255, 48, 48, 255}   // colors.viz-meter-clip = #FF3030
	genColorVizGlow                     = color.RGBA{255, 200, 180, 255} // colors.viz-glow = #FFC8B4
	genColorFocusRing                   = color.RGBA{255, 166, 140, 255} // colors.focus-ring = #FFA68C
	genColorSliderThumbFill             = color.RGBA{252, 239, 208, 255} // colors.slider-thumb-fill = #FCEFD0
	genColorSliderThumbShadow           = color.RGBA{0, 0, 0, 255}       // colors.slider-thumb-shadow = #000000
	genColorSliderTrackFill             = color.RGBA{45, 56, 72, 255}    // colors.slider-track-fill = #2D3848
	genColorSliderFill                  = color.RGBA{197, 100, 72, 255}  // colors.slider-fill = #C56448
	genColorSidebarSectionBg            = color.RGBA{90, 104, 132, 255}  // colors.sidebar-section-bg = #5A6884
	genColorVizScopeTraceA              = color.RGBA{255, 140, 90, 255}  // colors.viz-scope-trace-a = #FF8C5A
	genColorVizScopeTraceB              = color.RGBA{128, 232, 255, 255} // colors.viz-scope-trace-b = #80E8FF
	genColorVizScopeTraceDiff           = color.RGBA{160, 224, 128, 255} // colors.viz-scope-trace-diff = #A0E080
	genColorVizScopeBg                  = color.RGBA{19, 23, 31, 255}    // colors.viz-scope-bg = #13171F
	genColorVizScopeTrigger             = color.RGBA{255, 224, 96, 255}  // colors.viz-scope-trigger = #FFE060
	genColorVizSpectrumPeakMarker       = color.RGBA{255, 232, 208, 255} // colors.viz-spectrum-peak-marker = #FFE8D0
	genColorPlayDesktopFill             = color.RGBA{64, 160, 96, 255}   // colors.play-desktop-fill = #40A060
	genColorPlayDesktopBorder           = color.RGBA{96, 208, 128, 255}  // colors.play-desktop-border = #60D080
	genColorStopDesktopFill             = color.RGBA{184, 44, 44, 255}   // colors.stop-desktop-fill = #B82C2C
	genColorStopDesktopBorder           = color.RGBA{224, 72, 72, 255}   // colors.stop-desktop-border = #E04848
	genColorStepperFill                 = color.RGBA{28, 48, 80, 255}    // colors.stepper-fill = #1C3050
	genColorStepperBorder               = color.RGBA{64, 128, 192, 255}  // colors.stepper-border = #4080C0
	genColorDisabledFill                = color.RGBA{45, 56, 72, 255}    // colors.disabled-fill = #2D3848
	genColorDestructiveConfirmFill      = color.RGBA{208, 48, 48, 255}   // colors.destructive-confirm-fill = #D03030
	genColorDestructiveConfirmBorder    = color.RGBA{255, 96, 96, 255}   // colors.destructive-confirm-border = #FF6060
	genColorMuteActiveBorder            = color.RGBA{216, 120, 72, 255}  // colors.mute-active-border = #D87848
	genColorSoloActiveBorder            = color.RGBA{255, 180, 152, 255} // colors.solo-active-border = #FFB498
	genColorFxActiveFill                = color.RGBA{20, 42, 80, 255}    // colors.fx-active-fill = #142A50
	genColorEqFilterActiveFill          = color.RGBA{197, 100, 72, 255}  // colors.eq-filter-active-fill = #C56448
	genColorEqFilterActiveBorder        = color.RGBA{255, 140, 90, 255}  // colors.eq-filter-active-border = #FF8C5A
	genColorTransportFollowOnFill       = color.RGBA{38, 44, 60, 255}    // colors.transport-follow-on-fill = #262C3C
	genColorTransportFollowOnBorderBase = color.RGBA{255, 166, 140, 255} // colors.transport-follow-on-border-base = #FFA68C
	genColorErrorText                   = color.RGBA{255, 88, 72, 255}   // colors.error-text = #FF5848
	genColorEqMuteActiveFill            = color.RGBA{184, 44, 44, 255}   // colors.eq-mute-active-fill = #B82C2C
	genColorSidebarChipFill             = color.RGBA{56, 72, 88, 255}    // colors.sidebar-chip-fill = #384858
	genColorSidebarChipBorder           = color.RGBA{120, 136, 160, 255} // colors.sidebar-chip-border = #7888A0
	genColorSidebarSwatchFallback       = color.RGBA{180, 192, 208, 255} // colors.sidebar-swatch-fallback = #B4C0D0
	genColorSidebarBadgeBg              = color.RGBA{26, 34, 56, 255}    // colors.sidebar-badge-bg = #1A2238
	genColorRowRackColorFallback        = color.RGBA{216, 224, 232, 255} // colors.row-rack-color-fallback = #D8E0E8
	genColorVizDebugEdge                = color.RGBA{255, 255, 0, 255}   // colors.viz-debug-edge = #FFFF00
	genColorVizDebugNode                = color.RGBA{255, 64, 128, 255}  // colors.viz-debug-node = #FF4080
	genColorVizPillFill                 = color.RGBA{26, 31, 44, 255}    // colors.viz-pill-fill = #1A1F2C
	genColorVizPillBorder               = color.RGBA{120, 136, 160, 255} // colors.viz-pill-border = #7888A0
	genColorVizConfirmGreen             = color.RGBA{64, 160, 96, 255}   // colors.viz-confirm-green = #40A060
	genColorVizCancelRed                = color.RGBA{140, 48, 48, 255}   // colors.viz-cancel-red = #8C3030
	genColorDividerBase                 = color.RGBA{160, 176, 200, 255} // colors.divider-base = #A0B0C8
	genColorDividerShadow               = color.RGBA{16, 20, 28, 255}    // colors.divider-shadow = #10141C
	genColorDividerHighlight            = color.RGBA{52, 59, 78, 255}    // colors.divider-highlight = #343B4E
	genColorDrumStripeEven              = color.RGBA{24, 28, 38, 255}    // colors.drum-stripe-even = #181C26
	genColorDrumStripeOdd               = color.RGBA{19, 23, 31, 255}    // colors.drum-stripe-odd = #13171F
	genColorDrumGlow                    = color.RGBA{255, 140, 90, 255}  // colors.drum-glow = #FF8C5A
	genColorDrumCellOff                 = color.RGBA{19, 23, 31, 255}    // colors.drum-cell-off = #13171F
	genColorDrumCellHighlight           = color.RGBA{252, 239, 208, 255} // colors.drum-cell-highlight = #FCEFD0
	genColorEqReadoutBg                 = color.RGBA{26, 36, 56, 255}    // colors.eq-readout-bg = #1A2438
	genColorPopupTextSecondary          = color.RGBA{184, 200, 208, 255} // colors.popup-text-secondary = #B8C8D0
	genColorScopeLabelDim               = color.RGBA{56, 68, 80, 255}    // colors.scope-label-dim = #384450
	genColorTransportBarBg              = color.RGBA{23, 27, 37, 255}    // colors.transport-bar-bg = #171B25
	genColorDimBlack                    = color.RGBA{0, 0, 0, 255}       // colors.dim-black = #000000
	genColorGridLine                    = color.RGBA{28, 36, 50, 255}    // colors.grid-line = #1C2432
	genColorGridHalf                    = color.RGBA{36, 44, 58, 255}    // colors.grid-half = #242C3A
	genColorGridQuarter                 = color.RGBA{44, 52, 66, 255}    // colors.grid-quarter = #2C3442
	genColorGridEighth                  = color.RGBA{52, 60, 74, 255}    // colors.grid-eighth = #343C4A
	genColorGridSixteenth               = color.RGBA{60, 68, 82, 255}    // colors.grid-sixteenth = #3C4452
	genColorGridThirtySecond            = color.RGBA{68, 76, 90, 255}    // colors.grid-thirty-second = #444C5A
	genColorNodeFill                    = color.RGBA{40, 42, 52, 255}    // colors.node-fill = #282A34
	genColorNodeBorder                  = color.RGBA{140, 142, 155, 255} // colors.node-border = #8C8E9B
	genColorEdgeColor                   = color.RGBA{120, 122, 140, 255} // colors.edge-color = #787A8C
	genColorSplitterHandle              = color.RGBA{200, 200, 210, 255} // colors.splitter-handle = #C8C8D2
	genColorSplitterHandleMobile        = color.RGBA{0, 140, 200, 255}   // colors.splitter-handle-mobile = #008CC8
	genColorSplitterGripLine            = color.RGBA{100, 100, 110, 255} // colors.splitter-grip-line = #64646E
	genColorSplitterGripLineHover       = color.RGBA{180, 180, 190, 255} // colors.splitter-grip-line-hover = #B4B4BE
	genColorTimelineTotalBg             = color.RGBA{12, 16, 28, 255}    // colors.timeline-total-bg = #0C101C
	genColorTimelineView                = color.RGBA{255, 160, 64, 255}  // colors.timeline-view = #FFA040
	genColorTimelineViewHi              = color.RGBA{255, 184, 80, 255}  // colors.timeline-view-hi = #FFB850
	genColorTimelineCursor              = color.RGBA{255, 200, 96, 255}  // colors.timeline-cursor = #FFC860
	genColorTimelineBeat                = color.RGBA{80, 82, 90, 255}    // colors.timeline-beat = #50525A
	genColorDrumMuteCell                = color.RGBA{100, 100, 110, 255} // colors.drum-mute-cell = #64646E
	genColorDrumMuteHighlight           = color.RGBA{180, 182, 190, 255} // colors.drum-mute-highlight = #B4B6BE
	genColorWaveTraceDry                = color.RGBA{120, 144, 176, 255} // colors.wave-trace-dry = #7890B0
	genColorEqZeroLine                  = color.RGBA{120, 120, 130, 255} // colors.eq-zero-line = #787882
	genColorMenuDeleteTint              = color.RGBA{220, 50, 50, 255}   // colors.menu-delete-tint = #DC3232
	genColorIncdecIconHi                = color.RGBA{255, 184, 96, 255}  // colors.incdec-icon-hi = #FFB860
)

// ── Spacing ───────────────────────────────────────────────────────────────
const (
	genSpacingXs       = 3  // spacing.xs
	genSpacingSm       = 6  // spacing.sm
	genSpacingMd       = 10 // spacing.md
	genSpacingLg       = 14 // spacing.lg
	genSpacingXl       = 20 // spacing.xl
	genSpacingXxl      = 28 // spacing.xxl
	genSpacingCluster  = 12 // spacing.cluster
	genSpacingBtnSm    = 28 // spacing.btn-sm
	genSpacingBtnMd    = 36 // spacing.btn-md
	genSpacingBtnLg    = 44 // spacing.btn-lg
	genSpacingTouchMin = 44 // spacing.touch-min
	genSpacingIconSm   = 16 // spacing.icon-sm
	genSpacingIconMd   = 20 // spacing.icon-md
	genSpacingIconLg   = 24 // spacing.icon-lg
)

// ── Rounded (corner radii) ────────────────────────────────────────────────
const (
	genRoundedSm   = 8   // rounded.sm
	genRoundedMd   = 12  // rounded.md
	genRoundedLg   = 16  // rounded.lg
	genRoundedXl   = 20  // rounded.xl
	genRoundedFull = 999 // rounded.full
)

// ── Icon system (logical 24-unit grid) ────────────────────────────────────
//
// Every IconID renders onto a square logical canvas of `genIconGrid` units.
// Stroke is fractional — converted to pixel width per icon size at render
// time as `genIconStrokeWeight * (renderSize / genIconGrid)`.
const (
	genIconGrid    = 24 // icon.grid
	genIconPadding = 2  // icon.padding
	genIconRadius  = 2  // icon.radius
)

// genIconStrokeWeight is float32 because the stroke is a fractional
// logical-unit weight (Lucide-style 1.75). Pixel sizes round to int but
// preserving the fraction here matters for proportional stroke at small
// icon sizes.
const genIconStroke float32 = 1.75 // icon.stroke

// ── Alpha buckets ─────────────────────────────────────────────────────────
//
// Pair with WithAlpha(token, bucket) — never inline a raw 0-255 alpha for
// chrome.
const (
	genAlphaFaint                uint8 = 25  // alpha.faint
	genAlphaSubtle               uint8 = 60  // alpha.subtle
	genAlphaMedium               uint8 = 90  // alpha.medium
	genAlphaStrong               uint8 = 180 // alpha.strong
	genAlphaOverlay              uint8 = 220 // alpha.overlay
	genAlphaBorderThin           uint8 = 8   // alpha.border-thin
	genAlphaBorderDefault        uint8 = 15  // alpha.border-default
	genAlphaBorderEmphasis       uint8 = 25  // alpha.border-emphasis
	genAlphaBorderPanel          uint8 = 20  // alpha.border-panel
	genAlphaAccentTint           uint8 = 50  // alpha.accent-tint
	genAlphaAccentOverlay        uint8 = 80  // alpha.accent-overlay
	genAlphaWhiteDecoration      uint8 = 30  // alpha.white-decoration
	genAlphaScrollbarThumb       uint8 = 40  // alpha.scrollbar-thumb
	genAlphaScrollbarThumbMobile uint8 = 50  // alpha.scrollbar-thumb-mobile
	genAlphaSidebarSection       uint8 = 100 // alpha.sidebar-section
	genAlphaSidebarChip          uint8 = 200 // alpha.sidebar-chip
	genAlphaRowRackZebra         uint8 = 10  // alpha.row-rack-zebra
	genAlphaRowRackSeparator     uint8 = 16  // alpha.row-rack-separator
	genAlphaRowRackDim           uint8 = 6   // alpha.row-rack-dim
	genAlphaTransportSeparator   uint8 = 12  // alpha.transport-separator
	genAlphaScopeLabelDim        uint8 = 120 // alpha.scope-label-dim
	genAlphaRowActive            uint8 = 153 // alpha.row-active
	genAlphaEdgeDefault          uint8 = 100 // alpha.edge-default
	genAlphaWaveTraceDry         uint8 = 100 // alpha.wave-trace-dry
	genAlphaEqZeroLine           uint8 = 80  // alpha.eq-zero-line
	genAlphaEqCurveFill          uint8 = 20  // alpha.eq-curve-fill
	genAlphaMuteHighlight        uint8 = 160 // alpha.mute-highlight
	genAlphaScrim                uint8 = 150 // alpha.scrim
	genAlphaSplitterGripHover    uint8 = 200 // alpha.splitter-grip-hover
	genAlphaSplitterHover        uint8 = 240 // alpha.splitter-hover
	genAlphaPanelNearOpaque      uint8 = 250 // alpha.panel-near-opaque
	genAlphaBeatGroupAlt         uint8 = 4   // alpha.beat-group-alt
)

// ── Instrument swatches (curated suggestion palette) ──────────────────────
//
// Per-row color picker reads these as suggested swatches above the free
// hue wheel. Beatmo-only extension; the chrome runtime ignores this set.
// Source order from DESIGN.md is preserved.
var (
	genInstrumentSwatchCoral    = color.RGBA{255, 140, 90, 255}  // instrumentSwatches.coral = #FF8C5A
	genInstrumentSwatchPeach    = color.RGBA{255, 180, 132, 255} // instrumentSwatches.peach = #FFB484
	genInstrumentSwatchMarigold = color.RGBA{255, 213, 106, 255} // instrumentSwatches.marigold = #FFD56A
	genInstrumentSwatchLime     = color.RGBA{168, 224, 122, 255} // instrumentSwatches.lime = #A8E07A
	genInstrumentSwatchMint     = color.RGBA{122, 224, 184, 255} // instrumentSwatches.mint = #7AE0B8
	genInstrumentSwatchAqua     = color.RGBA{122, 220, 224, 255} // instrumentSwatches.aqua = #7ADCE0
	genInstrumentSwatchSky      = color.RGBA{132, 184, 255, 255} // instrumentSwatches.sky = #84B8FF
	genInstrumentSwatchLavender = color.RGBA{168, 154, 255, 255} // instrumentSwatches.lavender = #A89AFF
	genInstrumentSwatchOrchid   = color.RGBA{216, 154, 255, 255} // instrumentSwatches.orchid = #D89AFF
	genInstrumentSwatchRose     = color.RGBA{255, 154, 200, 255} // instrumentSwatches.rose = #FF9AC8
	genInstrumentSwatchSand     = color.RGBA{212, 194, 154, 255} // instrumentSwatches.sand = #D4C29A
	genInstrumentSwatchSlate    = color.RGBA{154, 176, 200, 255} // instrumentSwatches.slate = #9AB0C8
)

// GenInstrumentSwatch is the public shape of an entry in
// genInstrumentSwatches; the type is exported so the consumer
// (instrument_palette.go) can range over the slice without import gymnastics.
type GenInstrumentSwatch struct {
	Name string
	RGBA color.RGBA
	Hex  string
}

var genInstrumentSwatches = []GenInstrumentSwatch{
	{Name: "coral", RGBA: genInstrumentSwatchCoral, Hex: "#FF8C5A"},
	{Name: "peach", RGBA: genInstrumentSwatchPeach, Hex: "#FFB484"},
	{Name: "marigold", RGBA: genInstrumentSwatchMarigold, Hex: "#FFD56A"},
	{Name: "lime", RGBA: genInstrumentSwatchLime, Hex: "#A8E07A"},
	{Name: "mint", RGBA: genInstrumentSwatchMint, Hex: "#7AE0B8"},
	{Name: "aqua", RGBA: genInstrumentSwatchAqua, Hex: "#7ADCE0"},
	{Name: "sky", RGBA: genInstrumentSwatchSky, Hex: "#84B8FF"},
	{Name: "lavender", RGBA: genInstrumentSwatchLavender, Hex: "#A89AFF"},
	{Name: "orchid", RGBA: genInstrumentSwatchOrchid, Hex: "#D89AFF"},
	{Name: "rose", RGBA: genInstrumentSwatchRose, Hex: "#FF9AC8"},
	{Name: "sand", RGBA: genInstrumentSwatchSand, Hex: "#D4C29A"},
	{Name: "slate", RGBA: genInstrumentSwatchSlate, Hex: "#9AB0C8"},
}

// ── Instrument default colors (per built-in id) ───────────────────────────
//
// Consumed by the chrome runtime (theme.go's instColors map) — each
// row whose instrument id appears here inherits this hex as its
// drum-cell tint, edge tint, and rack swatch unless the user picks
// a custom color. Source order from DESIGN.md is preserved.
var (
	genInstrumentDefaultKick  = color.RGBA{50, 170, 100, 255} // instrumentDefaults.kick = #32AA64
	genInstrumentDefaultSnare = color.RGBA{195, 72, 80, 255}  // instrumentDefaults.snare = #C34850
	genInstrumentDefaultHihat = color.RGBA{200, 168, 45, 255} // instrumentDefaults.hihat = #C8A82D
	genInstrumentDefaultTom   = color.RGBA{68, 100, 195, 255} // instrumentDefaults.tom = #4464C3
	genInstrumentDefaultClap  = color.RGBA{185, 68, 168, 255} // instrumentDefaults.clap = #B944A8
)

var genInstrumentDefaults = map[string]color.RGBA{
	"kick":  genInstrumentDefaultKick,
	"snare": genInstrumentDefaultSnare,
	"hihat": genInstrumentDefaultHihat,
	"tom":   genInstrumentDefaultTom,
	"clap":  genInstrumentDefaultClap,
}

// ── Instrument fallback palette (cycled for unknown ids) ──────────────────
//
// When an instrument id is not present in genInstrumentDefaults, the
// runtime cycles this slice. Source order matters; do not sort.
var (
	genInstrumentFallback0 = color.RGBA{68, 168, 168, 255} // instrumentFallbackPalette[0] = #44A8A8
	genInstrumentFallback1 = color.RGBA{170, 110, 68, 255} // instrumentFallbackPalette[1] = #AA6E44
	genInstrumentFallback2 = color.RGBA{110, 68, 168, 255} // instrumentFallbackPalette[2] = #6E44A8
	genInstrumentFallback3 = color.RGBA{170, 68, 110, 255} // instrumentFallbackPalette[3] = #AA446E
	genInstrumentFallback4 = color.RGBA{68, 168, 110, 255} // instrumentFallbackPalette[4] = #44A86E
)

var genInstrumentFallbackPalette = []color.RGBA{
	genInstrumentFallback0,
	genInstrumentFallback1,
	genInstrumentFallback2,
	genInstrumentFallback3,
	genInstrumentFallback4,
}

// ── Animations ────────────────────────────────────────────────────────────
//
// Three closed kinds emitted as three typed structs. Runtime helpers in
// animation_helpers.go consume these (DecayStep, SinPulse, FadeFactor).
// Editing DESIGN.md's animations: block and re-running the generator is
// the only way to change cadence — never inline magic numbers in draw
// call sites.

// ExpDecayAnim drives a per-frame exponential decay loop: v *= rate
// each tick; exit when v < threshold.
type ExpDecayAnim struct {
	Rate      float64
	Threshold float64
}

// SinPulseAnim drives a per-frame oscillator: out = base + amplitude *
// |sin(frame * frame-step)|. AlphaScale (uint8) is the optional
// 0..255 ceiling when the output drives an alpha channel.
type SinPulseAnim struct {
	FrameStep  float64
	Amplitude  float64
	Base       float64
	AlphaScale uint8
}

// FadeFactor is a 0..1 multiplier applied via fadeColor() at the call
// site. One typed alias per role keeps the call site readable.
type FadeFactor float64

var (
	genAnimHighlightDecay                = ExpDecayAnim{Rate: 0.8, Threshold: 0.02}                                  // animations.highlight-decay
	genAnimPlayheadPulse                 = SinPulseAnim{FrameStep: 0.05, Amplitude: 0.6, Base: 0.4, AlphaScale: 120} // animations.playhead-pulse
	genAnimSignalGlowOuter    FadeFactor = 0.3                                                                       // animations.signal-glow-outer
	genAnimNodeTriggerGlow    FadeFactor = 0.35                                                                      // animations.node-trigger-glow
	genAnimPlayheadColumnFade FadeFactor = 0.85                                                                      // animations.playhead-column-fade
	genAnimEdgeFaded          FadeFactor = 0.6                                                                       // animations.edge-faded
	genAnimHighlightFaded     FadeFactor = 0.5                                                                       // animations.highlight-faded
)

// ── Geometry ──────────────────────────────────────────────────────────────
//
// Theme-level visual sizes / multipliers / fractions. Profile-dependent
// sizes (nodeMinPx / nodeMaxPx / edgeThickMul) live in profileOverrides.
const (
	genGeomSignalGlowRadiusMultiplier = 1.5  // geometry.signal-glow-radius-multiplier
	genGeomEdgeArrowStepFraction      = 0.15 // geometry.edge-arrow-step-fraction
	genGeomNodeBorderThickness        = 1    // geometry.node-border-thickness
	genGeomHighlightBorderThickness   = 2    // geometry.highlight-border-thickness
	genGeomNodeRadius                 = 16   // geometry.node-radius
	genGeomSignalRadius               = 6    // geometry.signal-radius
)
