// Code generated by cmd/gen_design_tokens. DO NOT EDIT.
//
// Source of truth: DESIGN.md `profileOverrides:` block.
// Regenerate via: make gen-design-tokens

package ui

// profileValues is the generated container for profile-conditional design
// fields. layout_profile.go's builder functions read these values into
// the larger LayoutProfile struct. Fields here are dimensional / visual-
// style only; runtime feature toggles live in runtime_profile.go.
type profileValues struct {
	AccentStripeInsetY    int // profileOverrides.accentStripeInsetY
	AccentStripeWidth     int // profileOverrides.accentStripeWidth
	CloseButtonSize       int // profileOverrides.closeButtonSize
	ControlGap            int // profileOverrides.controlGap
	ControlGroupPad       int // profileOverrides.controlGroupPad
	ControlLeftInset      int // profileOverrides.controlLeftInset
	ControlPadding        int // profileOverrides.controlPadding
	DefaultTimelineBeats  int // profileOverrides.defaultTimelineBeats
	EdgeThickMul          int // profileOverrides.edgeThickMul
	EqDBInputH            int // profileOverrides.eqDBInputH
	EqHandleRadius        int // profileOverrides.eqHandleRadius
	EqSliderH             int // profileOverrides.eqSliderH
	FxToggleThumbD        int // profileOverrides.fxToggleThumbD
	FxToggleTrackH        int // profileOverrides.fxToggleTrackH
	FxToggleTrackW        int // profileOverrides.fxToggleTrackW
	GrabZone              int // profileOverrides.grabZone
	HeaderMaxH            int // profileOverrides.headerMaxH
	HeaderMinH            int // profileOverrides.headerMinH
	MinCellWidth          int // profileOverrides.minCellWidth
	MinTarget             int // profileOverrides.minTarget
	NodeMaxPx             int // profileOverrides.nodeMaxPx
	NodeMinPx             int // profileOverrides.nodeMinPx
	PopupBtnH             int // profileOverrides.popupBtnH
	PopupBtnW             int // profileOverrides.popupBtnW
	PopupCornerRadius     int // profileOverrides.popupCornerRadius
	PopupGap              int // profileOverrides.popupGap
	PopupPad              int // profileOverrides.popupPad
	PopupPanelW           int // profileOverrides.popupPanelW
	PopupSectionGap       int // profileOverrides.popupSectionGap
	RowControlBtnSize     int // profileOverrides.rowControlBtnSize
	RowHeight             int // profileOverrides.rowHeight
	SliderThumbH          int // profileOverrides.sliderThumbH
	SliderThumbW          int // profileOverrides.sliderThumbW
	SliderTrackH          int // profileOverrides.sliderTrackH
	SplitterGrabThreshold int // profileOverrides.splitterGrabThreshold
	SplitterHandleLen     int // profileOverrides.splitterHandleLen
	SplitterHandleThk     int // profileOverrides.splitterHandleThk
	SynthHeaderH          int // profileOverrides.synthHeaderH
	TimelineBarH          int // profileOverrides.timelineBarH
	TransportBtnSize      int // profileOverrides.transportBtnSize
}

var (
	genDesktopProfile = profileValues{
		AccentStripeInsetY:    0,
		AccentStripeWidth:     3,
		CloseButtonSize:       22,
		ControlGap:            2,
		ControlGroupPad:       3,
		ControlLeftInset:      12,
		ControlPadding:        4,
		DefaultTimelineBeats:  0,
		EdgeThickMul:          1,
		EqDBInputH:            14,
		EqHandleRadius:        16,
		EqSliderH:             14,
		FxToggleThumbD:        14,
		FxToggleTrackH:        18,
		FxToggleTrackW:        32,
		GrabZone:              5,
		HeaderMaxH:            40,
		HeaderMinH:            40,
		MinCellWidth:          2,
		MinTarget:             0,
		NodeMaxPx:             16,
		NodeMinPx:             8,
		PopupBtnH:             16,
		PopupBtnW:             18,
		PopupCornerRadius:     12,
		PopupGap:              4,
		PopupPad:              6,
		PopupPanelW:           220,
		PopupSectionGap:       4,
		RowControlBtnSize:     28,
		RowHeight:             36,
		SliderThumbH:          18,
		SliderThumbW:          12,
		SliderTrackH:          4,
		SplitterGrabThreshold: 0,
		SplitterHandleLen:     50,
		SplitterHandleThk:     8,
		SynthHeaderH:          48,
		TimelineBarH:          12,
		TransportBtnSize:      32,
	}
	genMobileProfile = profileValues{
		AccentStripeInsetY:    2,
		AccentStripeWidth:     5,
		CloseButtonSize:       28,
		ControlGap:            4,
		ControlGroupPad:       4,
		ControlLeftInset:      4,
		ControlPadding:        4,
		DefaultTimelineBeats:  8,
		EdgeThickMul:          2,
		EqDBInputH:            20,
		EqHandleRadius:        26,
		EqSliderH:             28,
		FxToggleThumbD:        18,
		FxToggleTrackH:        22,
		FxToggleTrackW:        40,
		GrabZone:              16,
		HeaderMaxH:            56,
		HeaderMinH:            56,
		MinCellWidth:          2,
		MinTarget:             44,
		NodeMaxPx:             20,
		NodeMinPx:             12,
		PopupBtnH:             36,
		PopupBtnW:             44,
		PopupCornerRadius:     16,
		PopupGap:              6,
		PopupPad:              10,
		PopupPanelW:           300,
		PopupSectionGap:       8,
		RowControlBtnSize:     36,
		RowHeight:             44,
		SliderThumbH:          24,
		SliderThumbW:          14,
		SliderTrackH:          6,
		SplitterGrabThreshold: 8,
		SplitterHandleLen:     56,
		SplitterHandleThk:     6,
		SynthHeaderH:          38,
		TimelineBarH:          14,
		TransportBtnSize:      44,
	}
)
