// Code generated by cmd/gen_design_tokens. DO NOT EDIT.
//
// Source of truth: DESIGN.md (YAML front matter).
// Regenerate via: make gen-design-tokens

package ui

import "image/color"

// ── Colors ─────────────────────────────────────────────────────────────────
//
// One variable per entry under DESIGN.md `colors:`. Alpha is always
// 255 here (Stitch only allows opaque #RRGGBB); semi-transparent uses
// compose these via WithAlpha() + a named bucket below.
var (
	genColorSunsetGold100               = color.RGBA{255, 233, 138, 255} // colors.sunset-gold-100 = #FFE98A
	genColorSunsetGold200               = color.RGBA{255, 211, 25, 255}  // colors.sunset-gold-200 = #FFD319
	genColorSunsetGold300               = color.RGBA{255, 179, 10, 255}  // colors.sunset-gold-300 = #FFB30A
	genColorSunsetGold400               = color.RGBA{255, 158, 31, 255}  // colors.sunset-gold-400 = #FF9E1F
	genColorSunsetGold500               = color.RGBA{245, 138, 18, 255}  // colors.sunset-gold-500 = #F58A12
	genColorTangerine100                = color.RGBA{255, 194, 153, 255} // colors.tangerine-100 = #FFC299
	genColorTangerine200                = color.RGBA{255, 158, 84, 255}  // colors.tangerine-200 = #FF9E54
	genColorTangerine300                = color.RGBA{255, 122, 61, 255}  // colors.tangerine-300 = #FF7A3D
	genColorTangerine400                = color.RGBA{255, 92, 42, 255}   // colors.tangerine-400 = #FF5C2A
	genColorTangerine500                = color.RGBA{232, 74, 31, 255}   // colors.tangerine-500 = #E84A1F
	genColorHotPink100                  = color.RGBA{255, 168, 224, 255} // colors.hot-pink-100 = #FFA8E0
	genColorHotPink200                  = color.RGBA{255, 106, 213, 255} // colors.hot-pink-200 = #FF6AD5
	genColorHotPink300                  = color.RGBA{255, 45, 158, 255}  // colors.hot-pink-300 = #FF2D9E
	genColorHotPink400                  = color.RGBA{238, 0, 221, 255}   // colors.hot-pink-400 = #EE00DD
	genColorHotPink500                  = color.RGBA{196, 0, 181, 255}   // colors.hot-pink-500 = #C400B5
	genColorOrchid100                   = color.RGBA{224, 168, 255, 255} // colors.orchid-100 = #E0A8FF
	genColorOrchid200                   = color.RGBA{194, 79, 255, 255}  // colors.orchid-200 = #C24FFF
	genColorOrchid300                   = color.RGBA{160, 48, 255, 255}  // colors.orchid-300 = #A030FF
	genColorOrchid400                   = color.RGBA{140, 30, 255, 255}  // colors.orchid-400 = #8C1EFF
	genColorOrchid500                   = color.RGBA{110, 18, 224, 255}  // colors.orchid-500 = #6E12E0
	genColorElectricBlue100             = color.RGBA{168, 200, 255, 255} // colors.electric-blue-100 = #A8C8FF
	genColorElectricBlue200             = color.RGBA{94, 138, 255, 255}  // colors.electric-blue-200 = #5E8AFF
	genColorElectricBlue300             = color.RGBA{58, 106, 240, 255}  // colors.electric-blue-300 = #3A6AF0
	genColorElectricBlue400             = color.RGBA{42, 95, 214, 255}   // colors.electric-blue-400 = #2A5FD6
	genColorElectricBlue500             = color.RGBA{30, 71, 181, 255}   // colors.electric-blue-500 = #1E47B5
	genColorCyan100                     = color.RGBA{154, 240, 255, 255} // colors.cyan-100 = #9AF0FF
	genColorCyan200                     = color.RGBA{63, 224, 232, 255}  // colors.cyan-200 = #3FE0E8
	genColorCyan300                     = color.RGBA{0, 200, 224, 255}   // colors.cyan-300 = #00C8E0
	genColorCyan400                     = color.RGBA{0, 168, 201, 255}   // colors.cyan-400 = #00A8C9
	genColorCyan500                     = color.RGBA{14, 115, 145, 255}  // colors.cyan-500 = #0E7391
	genColorMint100                     = color.RGBA{179, 245, 194, 255} // colors.mint-100 = #B3F5C2
	genColorMint200                     = color.RGBA{107, 232, 154, 255} // colors.mint-200 = #6BE89A
	genColorMint300                     = color.RGBA{63, 214, 122, 255}  // colors.mint-300 = #3FD67A
	genColorMint400                     = color.RGBA{43, 200, 92, 255}   // colors.mint-400 = #2BC85C
	genColorMint500                     = color.RGBA{31, 168, 74, 255}   // colors.mint-500 = #1FA84A
	genColorNightBg                     = color.RGBA{18, 10, 28, 255}    // colors.night-bg = #120A1C
	genColorNightSurface1               = color.RGBA{28, 18, 48, 255}    // colors.night-surface-1 = #1C1230
	genColorNightSurface2               = color.RGBA{40, 26, 64, 255}    // colors.night-surface-2 = #281A40
	genColorNightSurface3               = color.RGBA{56, 35, 84, 255}    // colors.night-surface-3 = #382354
	genColorNightSurfaceOverlay         = color.RGBA{31, 20, 56, 255}    // colors.night-surface-overlay = #1F1438
	genColorNightTextHi                 = color.RGBA{253, 242, 255, 255} // colors.night-text-hi = #FDF2FF
	genColorNightTextMid                = color.RGBA{201, 184, 214, 255} // colors.night-text-mid = #C9B8D6
	genColorNightTextDim                = color.RGBA{138, 122, 156, 255} // colors.night-text-dim = #8A7A9C
	genColorPrimary                     = color.RGBA{0, 200, 224, 255}   // colors.primary = #00C8E0
	genColorPrimaryBright               = color.RGBA{63, 224, 232, 255}  // colors.primary-bright = #3FE0E8
	genColorPrimaryDim                  = color.RGBA{0, 168, 201, 255}   // colors.primary-dim = #00A8C9
	genColorBackground                  = color.RGBA{18, 10, 28, 255}    // colors.background = #120A1C
	genColorSurface1                    = color.RGBA{28, 18, 48, 255}    // colors.surface-1 = #1C1230
	genColorSurface2                    = color.RGBA{40, 26, 64, 255}    // colors.surface-2 = #281A40
	genColorSurface3                    = color.RGBA{56, 35, 84, 255}    // colors.surface-3 = #382354
	genColorSurfaceOverlay              = color.RGBA{31, 20, 56, 255}    // colors.surface-overlay = #1F1438
	genColorOnSurface                   = color.RGBA{253, 242, 255, 255} // colors.on-surface = #FDF2FF
	genColorOnSurfaceMuted              = color.RGBA{201, 184, 214, 255} // colors.on-surface-muted = #C9B8D6
	genColorOnSurfaceDisabled           = color.RGBA{138, 122, 156, 255} // colors.on-surface-disabled = #8A7A9C
	genColorOnSurfaceAccent             = color.RGBA{0, 200, 224, 255}   // colors.on-surface-accent = #00C8E0
	genColorBorder                      = color.RGBA{255, 255, 255, 255} // colors.border = #FFFFFF
	genColorSuccess                     = color.RGBA{63, 214, 122, 255}  // colors.success = #3FD67A
	genColorError                       = color.RGBA{255, 92, 42, 255}   // colors.error = #FF5C2A
	genColorMute                        = color.RGBA{196, 0, 181, 255}   // colors.mute = #C400B5
	genColorDestructive                 = color.RGBA{232, 74, 31, 255}   // colors.destructive = #E84A1F
	genColorDestructiveBorder           = color.RGBA{255, 92, 42, 255}   // colors.destructive-border = #FF5C2A
	genColorRecordIdle                  = color.RGBA{232, 74, 31, 255}   // colors.record-idle = #E84A1F
	genColorRecordActive                = color.RGBA{255, 92, 42, 255}   // colors.record-active = #FF5C2A
	genColorVizBg                       = color.RGBA{18, 10, 28, 255}    // colors.viz-bg = #120A1C
	genColorVizBar                      = color.RGBA{0, 200, 224, 255}   // colors.viz-bar = #00C8E0
	genColorVizBarPeak                  = color.RGBA{154, 240, 255, 255} // colors.viz-bar-peak = #9AF0FF
	genColorVizCurve                    = color.RGBA{0, 200, 224, 255}   // colors.viz-curve = #00C8E0
	genColorVizWaveA                    = color.RGBA{63, 224, 232, 255}  // colors.viz-wave-a = #3FE0E8
	genColorVizWaveB                    = color.RGBA{138, 122, 156, 255} // colors.viz-wave-b = #8A7A9C
	genColorVizMeterGreen               = color.RGBA{63, 214, 122, 255}  // colors.viz-meter-green = #3FD67A
	genColorVizMeterYellow              = color.RGBA{255, 211, 25, 255}  // colors.viz-meter-yellow = #FFD319
	genColorVizMeterRed                 = color.RGBA{255, 92, 42, 255}   // colors.viz-meter-red = #FF5C2A
	genColorVizMeterBg                  = color.RGBA{28, 18, 48, 255}    // colors.viz-meter-bg = #1C1230
	genColorVizMeterClip                = color.RGBA{232, 74, 31, 255}   // colors.viz-meter-clip = #E84A1F
	genColorVizBass                     = color.RGBA{255, 122, 61, 255}  // colors.viz-bass = #FF7A3D
	genColorVizMids                     = color.RGBA{201, 184, 214, 255} // colors.viz-mids = #C9B8D6
	genColorVizTreble                   = color.RGBA{58, 106, 240, 255}  // colors.viz-treble = #3A6AF0
	genColorVizGlow                     = color.RGBA{154, 240, 255, 255} // colors.viz-glow = #9AF0FF
	genColorFocusRing                   = color.RGBA{255, 45, 158, 255}  // colors.focus-ring = #FF2D9E
	genColorSliderThumbFill             = color.RGBA{253, 242, 255, 255} // colors.slider-thumb-fill = #FDF2FF
	genColorSliderThumbShadow           = color.RGBA{0, 0, 0, 255}       // colors.slider-thumb-shadow = #000000
	genColorSliderTrackFill             = color.RGBA{40, 26, 64, 255}    // colors.slider-track-fill = #281A40
	genColorSliderFill                  = color.RGBA{0, 168, 201, 255}   // colors.slider-fill = #00A8C9
	genColorSidebarSectionBg            = color.RGBA{56, 35, 84, 255}    // colors.sidebar-section-bg = #382354
	genColorVizScopeTraceA              = color.RGBA{0, 200, 224, 255}   // colors.viz-scope-trace-a = #00C8E0
	genColorVizScopeTraceB              = color.RGBA{63, 224, 232, 255}  // colors.viz-scope-trace-b = #3FE0E8
	genColorVizScopeTraceDiff           = color.RGBA{63, 214, 122, 255}  // colors.viz-scope-trace-diff = #3FD67A
	genColorVizScopeBg                  = color.RGBA{18, 10, 28, 255}    // colors.viz-scope-bg = #120A1C
	genColorVizScopeTrigger             = color.RGBA{255, 211, 25, 255}  // colors.viz-scope-trigger = #FFD319
	genColorVizSpectrumPeakMarker       = color.RGBA{253, 242, 255, 255} // colors.viz-spectrum-peak-marker = #FDF2FF
	genColorPlayDesktopFill             = color.RGBA{43, 200, 92, 255}   // colors.play-desktop-fill = #2BC85C
	genColorPlayDesktopBorder           = color.RGBA{63, 214, 122, 255}  // colors.play-desktop-border = #3FD67A
	genColorStopDesktopFill             = color.RGBA{232, 74, 31, 255}   // colors.stop-desktop-fill = #E84A1F
	genColorStopDesktopBorder           = color.RGBA{255, 92, 42, 255}   // colors.stop-desktop-border = #FF5C2A
	genColorStepperFill                 = color.RGBA{28, 18, 48, 255}    // colors.stepper-fill = #1C1230
	genColorStepperBorder               = color.RGBA{0, 168, 201, 255}   // colors.stepper-border = #00A8C9
	genColorDisabledFill                = color.RGBA{40, 26, 64, 255}    // colors.disabled-fill = #281A40
	genColorDestructiveConfirmFill      = color.RGBA{232, 74, 31, 255}   // colors.destructive-confirm-fill = #E84A1F
	genColorDestructiveConfirmBorder    = color.RGBA{255, 92, 42, 255}   // colors.destructive-confirm-border = #FF5C2A
	genColorMuteActiveBorder            = color.RGBA{255, 106, 213, 255} // colors.mute-active-border = #FF6AD5
	genColorSoloActiveBorder            = color.RGBA{63, 224, 232, 255}  // colors.solo-active-border = #3FE0E8
	genColorFxActiveFill                = color.RGBA{40, 26, 64, 255}    // colors.fx-active-fill = #281A40
	genColorEqFilterActiveFill          = color.RGBA{0, 168, 201, 255}   // colors.eq-filter-active-fill = #00A8C9
	genColorEqFilterActiveBorder        = color.RGBA{0, 200, 224, 255}   // colors.eq-filter-active-border = #00C8E0
	genColorTransportFollowOnFill       = color.RGBA{40, 26, 64, 255}    // colors.transport-follow-on-fill = #281A40
	genColorTransportFollowOnBorderBase = color.RGBA{63, 224, 232, 255}  // colors.transport-follow-on-border-base = #3FE0E8
	genColorErrorText                   = color.RGBA{255, 92, 42, 255}   // colors.error-text = #FF5C2A
	genColorEqMuteActiveFill            = color.RGBA{232, 74, 31, 255}   // colors.eq-mute-active-fill = #E84A1F
	genColorSidebarChipFill             = color.RGBA{56, 35, 84, 255}    // colors.sidebar-chip-fill = #382354
	genColorSidebarChipBorder           = color.RGBA{138, 122, 156, 255} // colors.sidebar-chip-border = #8A7A9C
	genColorSidebarSwatchFallback       = color.RGBA{201, 184, 214, 255} // colors.sidebar-swatch-fallback = #C9B8D6
	genColorSidebarBadgeBg              = color.RGBA{28, 18, 48, 255}    // colors.sidebar-badge-bg = #1C1230
	genColorRowRackColorFallback        = color.RGBA{253, 242, 255, 255} // colors.row-rack-color-fallback = #FDF2FF
	genColorVizDebugEdge                = color.RGBA{255, 211, 25, 255}  // colors.viz-debug-edge = #FFD319
	genColorVizDebugNode                = color.RGBA{255, 92, 42, 255}   // colors.viz-debug-node = #FF5C2A
	genColorVizPillFill                 = color.RGBA{28, 18, 48, 255}    // colors.viz-pill-fill = #1C1230
	genColorVizPillBorder               = color.RGBA{138, 122, 156, 255} // colors.viz-pill-border = #8A7A9C
	genColorVizConfirmGreen             = color.RGBA{63, 214, 122, 255}  // colors.viz-confirm-green = #3FD67A
	genColorVizCancelRed                = color.RGBA{232, 74, 31, 255}   // colors.viz-cancel-red = #E84A1F
	genColorDividerBase                 = color.RGBA{253, 242, 255, 255} // colors.divider-base = #FDF2FF
	genColorDividerShadow               = color.RGBA{0, 0, 0, 255}       // colors.divider-shadow = #000000
	genColorDividerHighlight            = color.RGBA{56, 35, 84, 255}    // colors.divider-highlight = #382354
	genColorDrumStripeEven              = color.RGBA{28, 18, 48, 255}    // colors.drum-stripe-even = #1C1230
	genColorDrumStripeOdd               = color.RGBA{18, 10, 28, 255}    // colors.drum-stripe-odd = #120A1C
	genColorDrumGlow                    = color.RGBA{0, 200, 224, 255}   // colors.drum-glow = #00C8E0
	genColorDrumCellOff                 = color.RGBA{40, 26, 64, 255}    // colors.drum-cell-off = #281A40
	genColorDrumCellHighlight           = color.RGBA{253, 242, 255, 255} // colors.drum-cell-highlight = #FDF2FF
	genColorEqReadoutBg                 = color.RGBA{28, 18, 48, 255}    // colors.eq-readout-bg = #1C1230
	genColorPopupTextSecondary          = color.RGBA{201, 184, 214, 255} // colors.popup-text-secondary = #C9B8D6
	genColorScopeLabelDim               = color.RGBA{56, 35, 84, 255}    // colors.scope-label-dim = #382354
	genColorTransportBarBg              = color.RGBA{18, 10, 28, 255}    // colors.transport-bar-bg = #120A1C
	genColorDimBlack                    = color.RGBA{0, 0, 0, 255}       // colors.dim-black = #000000
	genColorGridLine                    = color.RGBA{28, 18, 48, 255}    // colors.grid-line = #1C1230
	genColorGridHalf                    = color.RGBA{28, 18, 48, 255}    // colors.grid-half = #1C1230
	genColorGridQuarter                 = color.RGBA{40, 26, 64, 255}    // colors.grid-quarter = #281A40
	genColorGridEighth                  = color.RGBA{40, 26, 64, 255}    // colors.grid-eighth = #281A40
	genColorGridSixteenth               = color.RGBA{56, 35, 84, 255}    // colors.grid-sixteenth = #382354
	genColorGridThirtySecond            = color.RGBA{56, 35, 84, 255}    // colors.grid-thirty-second = #382354
	genColorGridHorizon                 = color.RGBA{56, 35, 84, 255}    // colors.grid-horizon = #382354
	genColorNodeFill                    = color.RGBA{40, 26, 64, 255}    // colors.node-fill = #281A40
	genColorNodeBorder                  = color.RGBA{138, 122, 156, 255} // colors.node-border = #8A7A9C
	genColorEdgeColor                   = color.RGBA{138, 122, 156, 255} // colors.edge-color = #8A7A9C
	genColorSplitterHandle              = color.RGBA{0, 200, 224, 255}   // colors.splitter-handle = #00C8E0
	genColorTimelineTotalBg             = color.RGBA{18, 10, 28, 255}    // colors.timeline-total-bg = #120A1C
	genColorTimelineView                = color.RGBA{255, 158, 31, 255}  // colors.timeline-view = #FF9E1F
	genColorTimelineViewHi              = color.RGBA{255, 179, 10, 255}  // colors.timeline-view-hi = #FFB30A
	genColorTimelineCursor              = color.RGBA{255, 211, 25, 255}  // colors.timeline-cursor = #FFD319
	genColorTimelineBeat                = color.RGBA{138, 122, 156, 255} // colors.timeline-beat = #8A7A9C
	genColorDrumMuteCell                = color.RGBA{138, 122, 156, 255} // colors.drum-mute-cell = #8A7A9C
	genColorDrumMuteHighlight           = color.RGBA{253, 242, 255, 255} // colors.drum-mute-highlight = #FDF2FF
	genColorWaveTraceDry                = color.RGBA{138, 122, 156, 255} // colors.wave-trace-dry = #8A7A9C
	genColorEqZeroLine                  = color.RGBA{138, 122, 156, 255} // colors.eq-zero-line = #8A7A9C
	genColorMenuDeleteTint              = color.RGBA{232, 74, 31, 255}   // colors.menu-delete-tint = #E84A1F
	genColorIncdecIconHi                = color.RGBA{0, 200, 224, 255}   // colors.incdec-icon-hi = #00C8E0
)

// ── Spacing ───────────────────────────────────────────────────────────────
const (
	genSpacingXs       = 3  // spacing.xs
	genSpacingSm       = 6  // spacing.sm
	genSpacingMd       = 10 // spacing.md
	genSpacingLg       = 14 // spacing.lg
	genSpacingXl       = 20 // spacing.xl
	genSpacingXxl      = 28 // spacing.xxl
	genSpacingCluster  = 12 // spacing.cluster
	genSpacingBtnSm    = 28 // spacing.btn-sm
	genSpacingBtnMd    = 36 // spacing.btn-md
	genSpacingBtnLg    = 44 // spacing.btn-lg
	genSpacingTouchMin = 44 // spacing.touch-min
	genSpacingIconSm   = 16 // spacing.icon-sm
	genSpacingIconMd   = 20 // spacing.icon-md
	genSpacingIconLg   = 24 // spacing.icon-lg
)

// ── Rounded (corner radii) ────────────────────────────────────────────────
const (
	genRoundedXxs  = 4   // rounded.xxs
	genRoundedXs   = 6   // rounded.xs
	genRoundedSm   = 8   // rounded.sm
	genRoundedMd   = 12  // rounded.md
	genRoundedLg   = 16  // rounded.lg
	genRoundedXl   = 20  // rounded.xl
	genRoundedFull = 999 // rounded.full
)

// ── Icon system (logical 24-unit grid) ────────────────────────────────────
//
// Every IconID renders onto a square logical canvas of `genIconGrid` units.
// Stroke is fractional — converted to pixel width per icon size at render
// time as `genIconStrokeWeight * (renderSize / genIconGrid)`.
const (
	genIconGrid    = 24 // icon.grid
	genIconPadding = 2  // icon.padding
	genIconRadius  = 2  // icon.radius
)

// genIconStrokeWeight is float32 because the stroke is a fractional
// logical-unit weight (Lucide-style 1.75). Pixel sizes round to int but
// preserving the fraction here matters for proportional stroke at small
// icon sizes.
const genIconStroke float32 = 1.75 // icon.stroke

// ── Alpha buckets ─────────────────────────────────────────────────────────
//
// Pair with WithAlpha(token, bucket) — never inline a raw 0-255 alpha for
// chrome.
const (
	genAlphaFaint                uint8 = 25  // alpha.faint
	genAlphaSubtle               uint8 = 60  // alpha.subtle
	genAlphaMedium               uint8 = 90  // alpha.medium
	genAlphaStrong               uint8 = 180 // alpha.strong
	genAlphaOverlay              uint8 = 220 // alpha.overlay
	genAlphaBorderThin           uint8 = 8   // alpha.border-thin
	genAlphaBorderDefault        uint8 = 15  // alpha.border-default
	genAlphaBorderEmphasis       uint8 = 25  // alpha.border-emphasis
	genAlphaBorderPanel          uint8 = 20  // alpha.border-panel
	genAlphaAccentTint           uint8 = 50  // alpha.accent-tint
	genAlphaAccentOverlay        uint8 = 80  // alpha.accent-overlay
	genAlphaWhiteDecoration      uint8 = 30  // alpha.white-decoration
	genAlphaScrollbarThumb       uint8 = 40  // alpha.scrollbar-thumb
	genAlphaScrollbarThumbMobile uint8 = 50  // alpha.scrollbar-thumb-mobile
	genAlphaSidebarSection       uint8 = 100 // alpha.sidebar-section
	genAlphaSidebarChip          uint8 = 200 // alpha.sidebar-chip
	genAlphaRowRackZebra         uint8 = 10  // alpha.row-rack-zebra
	genAlphaRowRackSeparator     uint8 = 16  // alpha.row-rack-separator
	genAlphaRowRackDim           uint8 = 6   // alpha.row-rack-dim
	genAlphaTransportSeparator   uint8 = 12  // alpha.transport-separator
	genAlphaScopeLabelDim        uint8 = 120 // alpha.scope-label-dim
	genAlphaRowActive            uint8 = 153 // alpha.row-active
	genAlphaEdgeDefault          uint8 = 100 // alpha.edge-default
	genAlphaWaveTraceDry         uint8 = 100 // alpha.wave-trace-dry
	genAlphaEqZeroLine           uint8 = 80  // alpha.eq-zero-line
	genAlphaEqCurveFill          uint8 = 20  // alpha.eq-curve-fill
	genAlphaMuteHighlight        uint8 = 160 // alpha.mute-highlight
	genAlphaScrim                uint8 = 150 // alpha.scrim
	genAlphaSplitterHover        uint8 = 240 // alpha.splitter-hover
	genAlphaPanelNearOpaque      uint8 = 250 // alpha.panel-near-opaque
	genAlphaBeatGroupAlt         uint8 = 4   // alpha.beat-group-alt
	genAlphaMenuActiveTint       uint8 = 60  // alpha.menu-active-tint
	genAlphaMenuHeaderAccent     uint8 = 50  // alpha.menu-header-accent
)

// ── Instrument swatches (curated suggestion palette) ──────────────────────
//
// Per-row color picker reads these as suggested swatches above the free
// hue wheel. Beatmo-only extension; the chrome runtime ignores this set.
// Source order from DESIGN.md is preserved.
var (
	genInstrumentSwatchSunsetGold100   = color.RGBA{255, 233, 138, 255} // instrumentSwatches.sunset-gold-100 = #FFE98A
	genInstrumentSwatchSunsetGold200   = color.RGBA{255, 211, 25, 255}  // instrumentSwatches.sunset-gold-200 = #FFD319
	genInstrumentSwatchSunsetGold300   = color.RGBA{255, 179, 10, 255}  // instrumentSwatches.sunset-gold-300 = #FFB30A
	genInstrumentSwatchSunsetGold400   = color.RGBA{255, 158, 31, 255}  // instrumentSwatches.sunset-gold-400 = #FF9E1F
	genInstrumentSwatchSunsetGold500   = color.RGBA{245, 138, 18, 255}  // instrumentSwatches.sunset-gold-500 = #F58A12
	genInstrumentSwatchTangerine100    = color.RGBA{255, 194, 153, 255} // instrumentSwatches.tangerine-100 = #FFC299
	genInstrumentSwatchTangerine200    = color.RGBA{255, 158, 84, 255}  // instrumentSwatches.tangerine-200 = #FF9E54
	genInstrumentSwatchTangerine300    = color.RGBA{255, 122, 61, 255}  // instrumentSwatches.tangerine-300 = #FF7A3D
	genInstrumentSwatchTangerine400    = color.RGBA{255, 92, 42, 255}   // instrumentSwatches.tangerine-400 = #FF5C2A
	genInstrumentSwatchTangerine500    = color.RGBA{232, 74, 31, 255}   // instrumentSwatches.tangerine-500 = #E84A1F
	genInstrumentSwatchHotPink100      = color.RGBA{255, 168, 224, 255} // instrumentSwatches.hot-pink-100 = #FFA8E0
	genInstrumentSwatchHotPink200      = color.RGBA{255, 106, 213, 255} // instrumentSwatches.hot-pink-200 = #FF6AD5
	genInstrumentSwatchHotPink300      = color.RGBA{255, 45, 158, 255}  // instrumentSwatches.hot-pink-300 = #FF2D9E
	genInstrumentSwatchHotPink400      = color.RGBA{238, 0, 221, 255}   // instrumentSwatches.hot-pink-400 = #EE00DD
	genInstrumentSwatchHotPink500      = color.RGBA{196, 0, 181, 255}   // instrumentSwatches.hot-pink-500 = #C400B5
	genInstrumentSwatchOrchid100       = color.RGBA{224, 168, 255, 255} // instrumentSwatches.orchid-100 = #E0A8FF
	genInstrumentSwatchOrchid200       = color.RGBA{194, 79, 255, 255}  // instrumentSwatches.orchid-200 = #C24FFF
	genInstrumentSwatchOrchid300       = color.RGBA{160, 48, 255, 255}  // instrumentSwatches.orchid-300 = #A030FF
	genInstrumentSwatchOrchid400       = color.RGBA{140, 30, 255, 255}  // instrumentSwatches.orchid-400 = #8C1EFF
	genInstrumentSwatchOrchid500       = color.RGBA{110, 18, 224, 255}  // instrumentSwatches.orchid-500 = #6E12E0
	genInstrumentSwatchElectricBlue100 = color.RGBA{168, 200, 255, 255} // instrumentSwatches.electric-blue-100 = #A8C8FF
	genInstrumentSwatchElectricBlue200 = color.RGBA{94, 138, 255, 255}  // instrumentSwatches.electric-blue-200 = #5E8AFF
	genInstrumentSwatchElectricBlue300 = color.RGBA{58, 106, 240, 255}  // instrumentSwatches.electric-blue-300 = #3A6AF0
	genInstrumentSwatchElectricBlue400 = color.RGBA{42, 95, 214, 255}   // instrumentSwatches.electric-blue-400 = #2A5FD6
	genInstrumentSwatchElectricBlue500 = color.RGBA{30, 71, 181, 255}   // instrumentSwatches.electric-blue-500 = #1E47B5
	genInstrumentSwatchCyan100         = color.RGBA{154, 240, 255, 255} // instrumentSwatches.cyan-100 = #9AF0FF
	genInstrumentSwatchCyan200         = color.RGBA{63, 224, 232, 255}  // instrumentSwatches.cyan-200 = #3FE0E8
	genInstrumentSwatchCyan300         = color.RGBA{0, 200, 224, 255}   // instrumentSwatches.cyan-300 = #00C8E0
	genInstrumentSwatchCyan400         = color.RGBA{0, 168, 201, 255}   // instrumentSwatches.cyan-400 = #00A8C9
	genInstrumentSwatchCyan500         = color.RGBA{14, 115, 145, 255}  // instrumentSwatches.cyan-500 = #0E7391
	genInstrumentSwatchMint100         = color.RGBA{179, 245, 194, 255} // instrumentSwatches.mint-100 = #B3F5C2
	genInstrumentSwatchMint200         = color.RGBA{107, 232, 154, 255} // instrumentSwatches.mint-200 = #6BE89A
	genInstrumentSwatchMint300         = color.RGBA{63, 214, 122, 255}  // instrumentSwatches.mint-300 = #3FD67A
	genInstrumentSwatchMint400         = color.RGBA{43, 200, 92, 255}   // instrumentSwatches.mint-400 = #2BC85C
	genInstrumentSwatchMint500         = color.RGBA{31, 168, 74, 255}   // instrumentSwatches.mint-500 = #1FA84A
)

// GenInstrumentSwatch is the public shape of an entry in
// genInstrumentSwatches; the type is exported so the consumer
// (instrument_palette.go) can range over the slice without import gymnastics.
type GenInstrumentSwatch struct {
	Name string
	RGBA color.RGBA
	Hex  string
}

var genInstrumentSwatches = []GenInstrumentSwatch{
	{Name: "sunset-gold-100", RGBA: genInstrumentSwatchSunsetGold100, Hex: "#FFE98A"},
	{Name: "sunset-gold-200", RGBA: genInstrumentSwatchSunsetGold200, Hex: "#FFD319"},
	{Name: "sunset-gold-300", RGBA: genInstrumentSwatchSunsetGold300, Hex: "#FFB30A"},
	{Name: "sunset-gold-400", RGBA: genInstrumentSwatchSunsetGold400, Hex: "#FF9E1F"},
	{Name: "sunset-gold-500", RGBA: genInstrumentSwatchSunsetGold500, Hex: "#F58A12"},
	{Name: "tangerine-100", RGBA: genInstrumentSwatchTangerine100, Hex: "#FFC299"},
	{Name: "tangerine-200", RGBA: genInstrumentSwatchTangerine200, Hex: "#FF9E54"},
	{Name: "tangerine-300", RGBA: genInstrumentSwatchTangerine300, Hex: "#FF7A3D"},
	{Name: "tangerine-400", RGBA: genInstrumentSwatchTangerine400, Hex: "#FF5C2A"},
	{Name: "tangerine-500", RGBA: genInstrumentSwatchTangerine500, Hex: "#E84A1F"},
	{Name: "hot-pink-100", RGBA: genInstrumentSwatchHotPink100, Hex: "#FFA8E0"},
	{Name: "hot-pink-200", RGBA: genInstrumentSwatchHotPink200, Hex: "#FF6AD5"},
	{Name: "hot-pink-300", RGBA: genInstrumentSwatchHotPink300, Hex: "#FF2D9E"},
	{Name: "hot-pink-400", RGBA: genInstrumentSwatchHotPink400, Hex: "#EE00DD"},
	{Name: "hot-pink-500", RGBA: genInstrumentSwatchHotPink500, Hex: "#C400B5"},
	{Name: "orchid-100", RGBA: genInstrumentSwatchOrchid100, Hex: "#E0A8FF"},
	{Name: "orchid-200", RGBA: genInstrumentSwatchOrchid200, Hex: "#C24FFF"},
	{Name: "orchid-300", RGBA: genInstrumentSwatchOrchid300, Hex: "#A030FF"},
	{Name: "orchid-400", RGBA: genInstrumentSwatchOrchid400, Hex: "#8C1EFF"},
	{Name: "orchid-500", RGBA: genInstrumentSwatchOrchid500, Hex: "#6E12E0"},
	{Name: "electric-blue-100", RGBA: genInstrumentSwatchElectricBlue100, Hex: "#A8C8FF"},
	{Name: "electric-blue-200", RGBA: genInstrumentSwatchElectricBlue200, Hex: "#5E8AFF"},
	{Name: "electric-blue-300", RGBA: genInstrumentSwatchElectricBlue300, Hex: "#3A6AF0"},
	{Name: "electric-blue-400", RGBA: genInstrumentSwatchElectricBlue400, Hex: "#2A5FD6"},
	{Name: "electric-blue-500", RGBA: genInstrumentSwatchElectricBlue500, Hex: "#1E47B5"},
	{Name: "cyan-100", RGBA: genInstrumentSwatchCyan100, Hex: "#9AF0FF"},
	{Name: "cyan-200", RGBA: genInstrumentSwatchCyan200, Hex: "#3FE0E8"},
	{Name: "cyan-300", RGBA: genInstrumentSwatchCyan300, Hex: "#00C8E0"},
	{Name: "cyan-400", RGBA: genInstrumentSwatchCyan400, Hex: "#00A8C9"},
	{Name: "cyan-500", RGBA: genInstrumentSwatchCyan500, Hex: "#0E7391"},
	{Name: "mint-100", RGBA: genInstrumentSwatchMint100, Hex: "#B3F5C2"},
	{Name: "mint-200", RGBA: genInstrumentSwatchMint200, Hex: "#6BE89A"},
	{Name: "mint-300", RGBA: genInstrumentSwatchMint300, Hex: "#3FD67A"},
	{Name: "mint-400", RGBA: genInstrumentSwatchMint400, Hex: "#2BC85C"},
	{Name: "mint-500", RGBA: genInstrumentSwatchMint500, Hex: "#1FA84A"},
}

// ── Instrument color sequence (canonical, ordered, finite) ────────────────
//
// THE single predictable series every circuit's instrument colors (and thus
// node + edge colors) are derived from: row N takes
// genInstrumentSequence[N % len]. Resolved from DESIGN.md instrumentSequence:
// (swatch names in warm↔cool order). The internal/templates package gets the
// identical series as templates.InstrumentSequence — both walk the same list.
var genInstrumentSequence = []color.RGBA{
	{238, 0, 221, 255},   // instrumentSequence.hot-pink-400 = #EE00DD
	{0, 200, 224, 255},   // instrumentSequence.cyan-300 = #00C8E0
	{255, 211, 25, 255},  // instrumentSequence.sunset-gold-200 = #FFD319
	{160, 48, 255, 255},  // instrumentSequence.orchid-300 = #A030FF
	{63, 214, 122, 255},  // instrumentSequence.mint-300 = #3FD67A
	{58, 106, 240, 255},  // instrumentSequence.electric-blue-300 = #3A6AF0
	{255, 122, 61, 255},  // instrumentSequence.tangerine-300 = #FF7A3D
	{255, 106, 213, 255}, // instrumentSequence.hot-pink-200 = #FF6AD5
}

// ── Instrument default colors (per built-in id) ───────────────────────────
//
// Consumed by the chrome runtime (theme.go's instColors map) — each
// row whose instrument id appears here inherits this hex as its
// drum-cell tint, edge tint, and rack swatch unless the user picks
// a custom color. Source order from DESIGN.md is preserved.
var (
	genInstrumentDefaultKick  = color.RGBA{255, 122, 61, 255} // instrumentDefaults.kick = #FF7A3D
	genInstrumentDefaultSnare = color.RGBA{238, 0, 221, 255}  // instrumentDefaults.snare = #EE00DD
	genInstrumentDefaultHihat = color.RGBA{255, 211, 25, 255} // instrumentDefaults.hihat = #FFD319
	genInstrumentDefaultTom   = color.RGBA{140, 30, 255, 255} // instrumentDefaults.tom = #8C1EFF
	genInstrumentDefaultClap  = color.RGBA{0, 200, 224, 255}  // instrumentDefaults.clap = #00C8E0
)

var genInstrumentDefaults = map[string]color.RGBA{
	"kick":  genInstrumentDefaultKick,
	"snare": genInstrumentDefaultSnare,
	"hihat": genInstrumentDefaultHihat,
	"tom":   genInstrumentDefaultTom,
	"clap":  genInstrumentDefaultClap,
}

// ── Instrument fallback palette (cycled for unknown ids) ──────────────────
//
// When an instrument id is not present in genInstrumentDefaults, the
// runtime cycles this slice. Source order matters; do not sort.
var (
	genInstrumentFallback0 = color.RGBA{63, 214, 122, 255}  // instrumentFallbackPalette[0] = #3FD67A
	genInstrumentFallback1 = color.RGBA{255, 106, 213, 255} // instrumentFallbackPalette[1] = #FF6AD5
	genInstrumentFallback2 = color.RGBA{42, 95, 214, 255}   // instrumentFallbackPalette[2] = #2A5FD6
	genInstrumentFallback3 = color.RGBA{194, 79, 255, 255}  // instrumentFallbackPalette[3] = #C24FFF
	genInstrumentFallback4 = color.RGBA{255, 179, 10, 255}  // instrumentFallbackPalette[4] = #FFB30A
)

var genInstrumentFallbackPalette = []color.RGBA{
	genInstrumentFallback0,
	genInstrumentFallback1,
	genInstrumentFallback2,
	genInstrumentFallback3,
	genInstrumentFallback4,
}

// ── Animations ────────────────────────────────────────────────────────────
//
// Three closed kinds emitted as three typed structs. Runtime helpers in
// animation_helpers.go consume these (DecayStep, SinPulse, FadeFactor).
// Editing DESIGN.md's animations: block and re-running the generator is
// the only way to change cadence — never inline magic numbers in draw
// call sites.

// ExpDecayAnim drives a per-frame exponential decay loop: v *= rate
// each tick; exit when v < threshold.
type ExpDecayAnim struct {
	Rate      float64
	Threshold float64
}

// SinPulseAnim drives a per-frame oscillator: out = base + amplitude *
// |sin(frame * frame-step)|. AlphaScale (uint8) is the optional
// 0..255 ceiling when the output drives an alpha channel.
type SinPulseAnim struct {
	FrameStep  float64
	Amplitude  float64
	Base       float64
	AlphaScale uint8
}

// FadeFactor is a 0..1 multiplier applied via fadeColor() at the call
// site. One typed alias per role keeps the call site readable.
type FadeFactor float64

var (
	genAnimHighlightDecay                = ExpDecayAnim{Rate: 0.8, Threshold: 0.02}                                  // animations.highlight-decay
	genAnimButtonPressDecay              = ExpDecayAnim{Rate: 0.6, Threshold: 0.01}                                  // animations.button-press-decay
	genAnimButtonHoverFade               = ExpDecayAnim{Rate: 0.65, Threshold: 0.01}                                 // animations.button-hover-fade
	genAnimPlayheadPulse                 = SinPulseAnim{FrameStep: 0.05, Amplitude: 0.6, Base: 0.4, AlphaScale: 120} // animations.playhead-pulse
	genAnimButtonTogglePulse             = SinPulseAnim{FrameStep: 0.08, Amplitude: 0.5, Base: 0.5, AlphaScale: 110} // animations.button-toggle-pulse
	genAnimSignalGlowOuter    FadeFactor = 0.3                                                                       // animations.signal-glow-outer
	genAnimNodeTriggerGlow    FadeFactor = 0.35                                                                      // animations.node-trigger-glow
	genAnimPlayheadColumnFade FadeFactor = 0.85                                                                      // animations.playhead-column-fade
	genAnimEdgeFaded          FadeFactor = 0.6                                                                       // animations.edge-faded
	genAnimHighlightFaded     FadeFactor = 0.5                                                                       // animations.highlight-faded
	genAnimButtonGlowRest     FadeFactor = 0.25                                                                      // animations.button-glow-rest
)

// ── Geometry ──────────────────────────────────────────────────────────────
//
// Theme-level visual sizes / multipliers / fractions. Profile-dependent
// sizes (nodeMinPx / nodeMaxPx / edgeThickMul) live in profileOverrides.
const (
	genGeomSignalGlowRadiusMultiplier = 1.5  // geometry.signal-glow-radius-multiplier
	genGeomEdgeArrowStepFraction      = 0.15 // geometry.edge-arrow-step-fraction
	genGeomNodeBorderThickness        = 1    // geometry.node-border-thickness
	genGeomHighlightBorderThickness   = 2    // geometry.highlight-border-thickness
	genGeomNodeRadius                 = 16   // geometry.node-radius
	genGeomSignalRadius               = 6    // geometry.signal-radius
	genGeomButtonInnerShadowPx        = 2    // geometry.button-inner-shadow-px
	genGeomButtonPressScale           = 0.92 // geometry.button-press-scale
	genGeomButtonReleaseOvershoot     = 1.03 // geometry.button-release-overshoot
	genGeomButtonHoverGlowSpread      = 3    // geometry.button-hover-glow-spread
	genGeomTransportMinBtnW           = 48   // geometry.transport-min-btn-w
)
