// Code generated by cmd/gen_design_tokens. DO NOT EDIT.
//
// Source of truth: DESIGN.md `components:` block.
// Regenerate via: make gen-design-tokens

package ui

import "image/color"

// ComponentID enum — one per DESIGN.md component entry, in source order.
const (
	ComponentButtonPrimary ComponentID = iota
	ComponentButtonSecondary
	ComponentButtonSecondaryActive
	ComponentButtonRowControl
	ComponentButtonRowControlMuteActive
	ComponentButtonRowControlSoloActive
	ComponentButtonRowControlFxActive
	ComponentButtonDestructive
	ComponentButtonDestructiveConfirm
	ComponentButtonDisabled
	ComponentPanel
	ComponentBottomSheet
	ComponentContextMenuItem
	ComponentContextMenuItemDestructive
	ComponentButtonRecordIdle
	ComponentButtonRecordActive
	ComponentButtonPlayActive
	ComponentSectionHeaderActive
	ComponentSplitterHandleMobile
	ComponentRowRack
	ComponentVizCanvas
	ComponentVizSpectrumBar
	ComponentVizSpectrumBarPeak
	ComponentVizEqCurve
	ComponentVizWaveTraceA
	ComponentVizWaveTraceB
	ComponentInputField
	ComponentInputFieldFocused
	ComponentButtonStepper
	ComponentButtonPlayDesktop
	ComponentButtonStopDesktop
	ComponentButtonDropdown
	ComponentButtonMissingInstrument
	ComponentButtonEqMute
	ComponentButtonEqMuteActive
	ComponentButtonEqFilterActive
	ComponentButtonTransportFollowOn
	ComponentButtonRowLabelMobile
	componentCount
)

// componentSpecs is the generated registry. Indexed by ComponentID.
var componentSpecs = [componentCount]ComponentSpec{
	ComponentButtonPrimary: {
		ID:       ComponentButtonPrimary,
		Category: CategoryButton,
		Fill:     color.RGBA{255, 140, 90, 255},
		Border: BorderRef{
			BaseColor: color.RGBA{255, 255, 255, 255},
			Alpha:     genAlphaWhiteDecoration,
		},
		Radius: 12,
		Height: 44,
	},
	ComponentButtonSecondary: {
		ID:       ComponentButtonSecondary,
		Category: CategoryButton,
		Fill:     color.RGBA{38, 44, 60, 255},
		Border: BorderRef{
			BaseColor: color.RGBA{255, 255, 255, 255},
			Alpha:     genAlphaBorderThin,
		},
		Radius:           12,
		Height:           36,
		IconColor:        color.RGBA{160, 176, 200, 255},
		HasIconColor:     true,
		TopEdgeHighlight: true,
		Interaction: Interaction{
			Hover: InteractionDelta{FillDelta: 12, BorderDelta: 20, HighlightDelta: 0},
			Press: InteractionDelta{FillDelta: -20, BorderDelta: 0, HighlightDelta: 10},
		},
	},
	ComponentButtonSecondaryActive: {
		ID:       ComponentButtonSecondaryActive,
		Category: CategoryButton,
		Fill:     color.RGBA{52, 59, 78, 255},
	},
	ComponentButtonRowControl: {
		ID:       ComponentButtonRowControl,
		Category: CategoryButton,
		Fill:     color.RGBA{38, 44, 60, 255},
		Border: BorderRef{
			BaseColor: color.RGBA{255, 255, 255, 255},
			Alpha:     genAlphaBorderThin,
		},
		Radius: 8,
		Height: 36,
		Interaction: Interaction{
			Hover: InteractionDelta{FillDelta: 12, BorderDelta: 20, HighlightDelta: 0},
			Press: InteractionDelta{FillDelta: -20, BorderDelta: 0, HighlightDelta: 10},
		},
	},
	ComponentButtonRowControlMuteActive: {
		ID:       ComponentButtonRowControlMuteActive,
		Category: CategoryButton,
		Fill:     color.RGBA{160, 72, 48, 255},
		Border: BorderRef{
			BaseColor: color.RGBA{216, 120, 72, 255},
			Alpha:     255,
		},
		Radius: 8,
		Height: 36,
	},
	ComponentButtonRowControlSoloActive: {
		ID:       ComponentButtonRowControlSoloActive,
		Category: CategoryButton,
		Fill:     color.RGBA{255, 180, 152, 255},
		Border: BorderRef{
			BaseColor: color.RGBA{255, 180, 152, 255},
			Alpha:     255,
		},
		Radius: 8,
		Height: 36,
	},
	ComponentButtonRowControlFxActive: {
		ID:       ComponentButtonRowControlFxActive,
		Category: CategoryButton,
		Fill:     color.RGBA{20, 42, 80, 255},
		Border: BorderRef{
			BaseColor: color.RGBA{255, 140, 90, 255},
			Alpha:     255,
		},
		Radius: 8,
		Height: 36,
	},
	ComponentButtonDestructive: {
		ID:       ComponentButtonDestructive,
		Category: CategoryButton,
		Fill:     color.RGBA{72, 20, 20, 255},
		Border: BorderRef{
			BaseColor: color.RGBA{160, 56, 48, 255},
			Alpha:     255,
		},
		Radius: 8,
		Height: 36,
	},
	ComponentButtonDestructiveConfirm: {
		ID:       ComponentButtonDestructiveConfirm,
		Category: CategoryButton,
		Fill:     color.RGBA{208, 48, 48, 255},
		Border: BorderRef{
			BaseColor: color.RGBA{255, 96, 96, 255},
			Alpha:     255,
		},
		Radius: 8,
		Height: 36,
	},
	ComponentButtonDisabled: {
		ID:       ComponentButtonDisabled,
		Category: CategoryButton,
		Fill:     color.RGBA{45, 56, 72, 255},
		Border: BorderRef{
			BaseColor: color.RGBA{255, 255, 255, 255},
			Alpha:     genAlphaBorderThin,
		},
		Radius: 8,
	},
	ComponentPanel: {
		ID:     ComponentPanel,
		Fill:   color.RGBA{31, 37, 51, 255},
		Radius: 12,
	},
	ComponentBottomSheet: {
		ID:     ComponentBottomSheet,
		Fill:   color.RGBA{31, 37, 51, 255},
		Radius: 20,
	},
	ComponentContextMenuItem: {
		ID:     ComponentContextMenuItem,
		Fill:   color.RGBA{31, 37, 51, 255},
		Height: 36,
	},
	ComponentContextMenuItemDestructive: {
		ID:   ComponentContextMenuItemDestructive,
		Fill: color.RGBA{31, 37, 51, 255},
	},
	ComponentButtonRecordIdle: {
		ID:     ComponentButtonRecordIdle,
		Fill:   color.RGBA{38, 44, 60, 255},
		Radius: 12,
		Height: 36,
	},
	ComponentButtonRecordActive: {
		ID:     ComponentButtonRecordActive,
		Fill:   color.RGBA{38, 44, 60, 255},
		Radius: 12,
		Height: 36,
	},
	ComponentButtonPlayActive: {
		ID:     ComponentButtonPlayActive,
		Fill:   color.RGBA{38, 44, 60, 255},
		Radius: 12,
		Height: 36,
	},
	ComponentSectionHeaderActive: {
		ID: ComponentSectionHeaderActive,
	},
	ComponentSplitterHandleMobile: {
		ID:     ComponentSplitterHandleMobile,
		Fill:   color.RGBA{197, 100, 72, 255},
		Radius: 8,
	},
	ComponentRowRack: {
		ID:   ComponentRowRack,
		Fill: color.RGBA{26, 31, 44, 255},
	},
	ComponentVizCanvas: {
		ID:     ComponentVizCanvas,
		Fill:   color.RGBA{19, 23, 31, 255},
		Radius: 8,
	},
	ComponentVizSpectrumBar: {
		ID:   ComponentVizSpectrumBar,
		Fill: color.RGBA{90, 200, 224, 255},
	},
	ComponentVizSpectrumBarPeak: {
		ID:   ComponentVizSpectrumBarPeak,
		Fill: color.RGBA{160, 224, 255, 255},
	},
	ComponentVizEqCurve: {
		ID: ComponentVizEqCurve,
	},
	ComponentVizWaveTraceA: {
		ID: ComponentVizWaveTraceA,
	},
	ComponentVizWaveTraceB: {
		ID: ComponentVizWaveTraceB,
	},
	ComponentInputField: {
		ID:       ComponentInputField,
		Category: CategoryInput,
		Fill:     color.RGBA{38, 44, 60, 255},
		Border: BorderRef{
			BaseColor: color.RGBA{255, 255, 255, 255},
			Alpha:     genAlphaBorderDefault,
		},
		Radius: 8,
		Interaction: Interaction{
			Focus: InteractionDelta{FillDelta: 30, BorderDelta: 80, HighlightDelta: 0},
		},
	},
	ComponentInputFieldFocused: {
		ID:       ComponentInputFieldFocused,
		Category: CategoryInput,
		Fill:     color.RGBA{38, 44, 60, 255},
		Border: BorderRef{
			BaseColor: color.RGBA{255, 255, 255, 255},
			Alpha:     genAlphaBorderEmphasis,
		},
	},
	ComponentButtonStepper: {
		ID:       ComponentButtonStepper,
		Category: CategoryButton,
		Fill:     color.RGBA{28, 48, 80, 255},
		Border: BorderRef{
			BaseColor: color.RGBA{64, 128, 192, 255},
			Alpha:     255,
		},
		Radius: 12,
		Height: 36,
	},
	ComponentButtonPlayDesktop: {
		ID:       ComponentButtonPlayDesktop,
		Category: CategoryButton,
		Fill:     color.RGBA{64, 160, 96, 255},
		Border: BorderRef{
			BaseColor: color.RGBA{96, 208, 128, 255},
			Alpha:     255,
		},
		Radius: 12,
		Height: 36,
	},
	ComponentButtonStopDesktop: {
		ID:       ComponentButtonStopDesktop,
		Category: CategoryButton,
		Fill:     color.RGBA{184, 44, 44, 255},
		Border: BorderRef{
			BaseColor: color.RGBA{224, 72, 72, 255},
			Alpha:     255,
		},
		Radius: 12,
		Height: 36,
	},
	ComponentButtonDropdown: {
		ID:       ComponentButtonDropdown,
		Category: CategoryButton,
		Fill:     color.RGBA{38, 44, 60, 255},
		Border: BorderRef{
			BaseColor: color.RGBA{255, 140, 90, 255},
			Alpha:     genAlphaAccentTint,
		},
		Radius: 12,
		Height: 36,
	},
	ComponentButtonMissingInstrument: {
		ID:       ComponentButtonMissingInstrument,
		Category: CategoryButton,
		Fill:     color.RGBA{255, 88, 72, 255},
		Border: BorderRef{
			BaseColor: color.RGBA{255, 255, 255, 255},
			Alpha:     genAlphaBorderDefault,
		},
		Radius: 8,
	},
	ComponentButtonEqMute: {
		ID:       ComponentButtonEqMute,
		Category: CategoryButton,
		Fill:     color.RGBA{52, 59, 78, 255},
		Border: BorderRef{
			BaseColor: color.RGBA{255, 255, 255, 255},
			Alpha:     genAlphaBorderDefault,
		},
		Radius: 8,
		Height: 36,
	},
	ComponentButtonEqMuteActive: {
		ID:       ComponentButtonEqMuteActive,
		Category: CategoryButton,
		Fill:     color.RGBA{184, 44, 44, 255},
		Border: BorderRef{
			BaseColor: color.RGBA{255, 255, 255, 255},
			Alpha:     genAlphaBorderDefault,
		},
		Radius: 8,
		Height: 36,
	},
	ComponentButtonEqFilterActive: {
		ID:       ComponentButtonEqFilterActive,
		Category: CategoryButton,
		Fill:     color.RGBA{197, 100, 72, 255},
		Border: BorderRef{
			BaseColor: color.RGBA{255, 140, 90, 255},
			Alpha:     255,
		},
		Radius: 8,
		Height: 36,
	},
	ComponentButtonTransportFollowOn: {
		ID:       ComponentButtonTransportFollowOn,
		Category: CategoryButton,
		Fill:     color.RGBA{38, 44, 60, 255},
		Border: BorderRef{
			BaseColor: color.RGBA{255, 166, 140, 255},
			Alpha:     genAlphaAccentOverlay,
		},
		Radius: 12,
		Height: 36,
	},
	ComponentButtonRowLabelMobile: {
		ID:       ComponentButtonRowLabelMobile,
		Category: CategoryButton,
		Fill:     color.RGBA{26, 31, 44, 255},
		Border: BorderRef{
			BaseColor: color.RGBA{255, 255, 255, 255},
			Alpha:     genAlphaBorderThin,
		},
		Radius: 8,
		Height: 36,
	},
}

// Spec returns the immutable ComponentSpec for the given ID. The returned
// value must not be mutated; copy if a one-off variant is needed.
func Spec(id ComponentID) ComponentSpec {
	if id < 0 || id >= componentCount {
		return ComponentSpec{}
	}
	return componentSpecs[id]
}
