//go:build !test && !js

// gen-chain-spec emits src/js/chain_spec.gen.js from the canonical
// CanonicalChainSpec declared in internal/audio (chain_spec.go). It is the
// single source of truth for the post-voice master/mix chain configuration
// (compressor params, soft-clip threshold, per-voice headroom, target sample
// rate) that desktop (Go/C) and browser (WebAudio) must share so the platforms
// sound the same.
//
// Usage:
//
//	cd src/go && go run ./cmd/gen-chain-spec > ../js/chain_spec.gen.js
//
// A drift test (internal/audio/chain_spec_test.go) regenerates and diffs so
// commits cannot land with a stale gen file. Mirrors cmd/gen-synth-abi.
package main

import (
	"bytes"
	"fmt"
	"os"

	"github.com/ingyamilmolinar/beatmo/internal/audio"
)

func main() {
	if _, err := os.Stdout.Write(generate()); err != nil {
		fmt.Fprintf(os.Stderr, "gen-chain-spec: write failed: %v\n", err)
		os.Exit(1)
	}
}

// generate renders the chain_spec.gen.js bytes. Split out so the drift test can
// compare against the committed file without shelling out.
func generate() []byte {
	s := audio.CanonicalChainSpec()
	var buf bytes.Buffer
	buf.WriteString("// Code generated by cmd/gen-chain-spec. DO NOT EDIT.\n")
	buf.WriteString("//\n")
	buf.WriteString("// Source of truth: src/go/internal/audio/chain_spec.go\n")
	buf.WriteString("// Regenerate: cd src/go && go run ./cmd/gen-chain-spec > ../js/chain_spec.gen.js\n")
	buf.WriteString("//\n")
	buf.WriteString("// The post-voice master/mix chain is implemented twice — Go/C on desktop,\n")
	buf.WriteString("// WebAudio nodes in audio.js. These constants keep both configured identically\n")
	buf.WriteString("// so the same instrument sounds the same on both platforms. audio.js reads\n")
	buf.WriteString("// them in ensureCompressor + ensureLimiter; chain_spec_parity.browser.test.js\n")
	buf.WriteString("// asserts the live WebAudio nodes match these values.\n")
	buf.WriteString("\n")
	buf.WriteString("// Master compressor. NOTE: audio.js DynamicsCompressorNode takes attack/\n")
	buf.WriteString("// release in SECONDS — divide the *Ms values by 1000.\n")
	buf.WriteString("export const CHAIN_SPEC = Object.freeze({\n")
	fmt.Fprintf(&buf, "  compressorThresholdDb: %s,\n", formatFloat(s.CompressorThresholdDB))
	fmt.Fprintf(&buf, "  compressorRatio: %s,\n", formatFloat(s.CompressorRatio))
	fmt.Fprintf(&buf, "  compressorAttackMs: %s,\n", formatFloat(s.CompressorAttackMs))
	fmt.Fprintf(&buf, "  compressorReleaseMs: %s,\n", formatFloat(s.CompressorReleaseMs))
	fmt.Fprintf(&buf, "  compressorKneeDb: %s,\n", formatFloat(s.CompressorKneeDB))
	fmt.Fprintf(&buf, "  softClipThreshold: %s,\n", formatFloat(s.SoftClipThreshold))
	fmt.Fprintf(&buf, "  voiceHeadroom: %s,\n", formatFloat(s.VoiceHeadroom))
	fmt.Fprintf(&buf, "  targetSampleRate: %d,\n", s.TargetSampleRate)
	buf.WriteString("});\n")
	return buf.Bytes()
}

// formatFloat renders v compactly: integers without a trailing decimal so the
// gen-file diff stays minimal. Mirrors cmd/gen-synth-abi.
func formatFloat(v float64) string {
	if v == float64(int64(v)) {
		return fmt.Sprintf("%d", int64(v))
	}
	return fmt.Sprintf("%g", v)
}
