package main

// densities.go — Phase 0 (audio-panel design-system compliance) generator:
// parse the `densities:` block of DESIGN.md and emit
// `design_density.gen.go` with one `densityValues` struct + one
// genXxxDensity variable per density (compact / comfortable / spacious).
//
// Mechanically identical to profiles.go but populates a parallel,
// orthogonal axis: `profileOverrides:` carries layout-arrangement
// decisions (panel orientation, hide-on-mobile chrome) while
// `densities:` carries control-sizing decisions (button heights,
// touch targets, knob diameters). The generated container is consumed
// by `internal/ui/density_profile.go`'s `densityValuesFor()` switch.

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"
	"strconv"
	"text/template"

	"gopkg.in/yaml.v3"
)

// densitySet is the parsed shape: map of density name → field name →
// integer value. Order is preserved by the generator's emit step
// (alphabetical by density, alphabetical by field within) for stable
// diffs.
type densitySet map[string]map[string]int

func parseDensities(node *yaml.Node) (densitySet, error) {
	out := densitySet{}
	if node == nil || node.Kind == 0 {
		return out, nil
	}
	if node.Kind != yaml.MappingNode {
		return nil, fmt.Errorf("densities: expected mapping (got kind %d)", node.Kind)
	}
	for i := 0; i+1 < len(node.Content); i += 2 {
		densityName := node.Content[i]
		densityBody := node.Content[i+1]
		if densityBody.Kind != yaml.MappingNode {
			return nil, fmt.Errorf("densities.%s: expected mapping (got kind %d)", densityName.Value, densityBody.Kind)
		}
		fields := map[string]int{}
		for j := 0; j+1 < len(densityBody.Content); j += 2 {
			k := densityBody.Content[j]
			v := densityBody.Content[j+1]
			if v.Kind != yaml.ScalarNode {
				return nil, fmt.Errorf("densities.%s.%s: expected scalar value", densityName.Value, k.Value)
			}
			n, err := strconv.Atoi(v.Value)
			if err != nil {
				return nil, fmt.Errorf("densities.%s.%s = %q: not an integer", densityName.Value, k.Value, v.Value)
			}
			fields[k.Value] = n
		}
		out[densityName.Value] = fields
	}
	return out, nil
}

func emitDensities(densities densitySet) ([]byte, error) {
	// Field union across all densities — every density must set every
	// field for stable struct emission. Missing fields error out so a
	// silent zero-default can't sneak in via a forgotten copy.
	fieldSet := map[string]bool{}
	for _, d := range densities {
		for k := range d {
			fieldSet[k] = true
		}
	}
	fields := make([]string, 0, len(fieldSet))
	for k := range fieldSet {
		fields = append(fields, k)
	}
	sort.Strings(fields)

	for densityName, d := range densities {
		for _, f := range fields {
			if _, ok := d[f]; !ok {
				return nil, fmt.Errorf("densities.%s: missing field %q (every density must set every field)", densityName, f)
			}
		}
	}

	densityNames := make([]string, 0, len(densities))
	for k := range densities {
		densityNames = append(densityNames, k)
	}
	sort.Strings(densityNames)

	type fieldOut struct {
		Ident   string // PascalCase Go identifier
		YAMLKey string
	}
	type densityOut struct {
		Ident  string // genXxxDensity, e.g. genCompactDensity
		Source string // YAML density name, e.g. "compact"
		Values map[string]int
	}
	fieldOuts := make([]fieldOut, len(fields))
	for i, f := range fields {
		fieldOuts[i] = fieldOut{Ident: pascal(f), YAMLKey: f}
	}
	densityOuts := make([]densityOut, len(densityNames))
	for i, name := range densityNames {
		densityOuts[i] = densityOut{
			Ident:  "gen" + pascal(name) + "Density",
			Source: name,
			Values: densities[name],
		}
	}

	tpl := template.Must(template.New("densities").Funcs(template.FuncMap{
		"value": func(d densityOut, key string) int { return d.Values[key] },
	}).Parse(densitiesTemplate))

	var buf bytes.Buffer
	data := struct {
		Fields    []fieldOut
		Densities []densityOut
	}{fieldOuts, densityOuts}
	if err := tpl.Execute(&buf, data); err != nil {
		return nil, err
	}
	return format.Source(buf.Bytes())
}

const densitiesTemplate = `// Code generated by cmd/gen_design_tokens. DO NOT EDIT.
//
// Source of truth: DESIGN.md ` + "`densities:`" + ` block.
// Regenerate via: make gen-design-tokens

package ui

// densityValues is the generated container for density-conditional
// design fields. density_profile.go's densityValuesFor() returns
// the right variable for the active Density. Fields here are the
// "size of interactive controls" subset of dimensional design tokens
// — selected for being density-tied (finger-vs-mouse), not
// screen-class-tied (viewport-narrow-vs-wide).
type densityValues struct {
{{- range .Fields}}
	{{.Ident}} int // densities.{{.YAMLKey}}
{{- end}}
}

var (
{{- range .Densities}}
	{{.Ident}} = densityValues{
{{- $d := . -}}
{{range $.Fields}}
		{{.Ident}}: {{value $d .YAMLKey}},
{{- end}}
	}
{{- end}}
)
`
