package main

// profiles.go — Phase 5a generator: parse the `profileOverrides:` block of
// DESIGN.md and emit `design_profile.gen.go` with one profileValues struct
// per profile (desktop / mobile). The generated file is consumed by
// `internal/ui/layout_profile.go`'s desktop/mobile builder functions for
// fields covered by the schema; remaining fields stay hand-coded until
// future migration sweeps.
//
// Phase 5a v1 covers a representative slice of dimensional fields
// (sizing primitives, popup sizing, transport/row-control button sizes).
// Phase 5a v2+ extends the schema field-by-field as appetite warrants.

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"
	"strconv"
	"text/template"

	"gopkg.in/yaml.v3"
)

// profileSet is the parsed shape: map of profile name → field name → integer value.
// Order is preserved by the generator's emit step (alphabetical by profile,
// alphabetical by field within) for stable diffs.
type profileSet map[string]map[string]int

func parseProfileOverrides(node *yaml.Node) (profileSet, error) {
	out := profileSet{}
	if node == nil || node.Kind == 0 {
		return out, nil
	}
	if node.Kind != yaml.MappingNode {
		return nil, fmt.Errorf("profileOverrides: expected mapping (got kind %d)", node.Kind)
	}
	for i := 0; i+1 < len(node.Content); i += 2 {
		profileName := node.Content[i]
		profileBody := node.Content[i+1]
		if profileBody.Kind != yaml.MappingNode {
			return nil, fmt.Errorf("profileOverrides.%s: expected mapping (got kind %d)", profileName.Value, profileBody.Kind)
		}
		fields := map[string]int{}
		for j := 0; j+1 < len(profileBody.Content); j += 2 {
			k := profileBody.Content[j]
			v := profileBody.Content[j+1]
			if v.Kind != yaml.ScalarNode {
				return nil, fmt.Errorf("profileOverrides.%s.%s: expected scalar value", profileName.Value, k.Value)
			}
			n, err := strconv.Atoi(v.Value)
			if err != nil {
				return nil, fmt.Errorf("profileOverrides.%s.%s = %q: not an integer", profileName.Value, k.Value, v.Value)
			}
			fields[k.Value] = n
		}
		out[profileName.Value] = fields
	}
	return out, nil
}

func emitProfiles(profiles profileSet) ([]byte, error) {
	// Collect the union of all field names across all profiles so the
	// emitted struct definition is profile-independent. Every profile
	// must set every field (validated below) — missing values are an
	// error to prevent silent zero-defaults sneaking in.
	fieldSet := map[string]bool{}
	for _, p := range profiles {
		for k := range p {
			fieldSet[k] = true
		}
	}
	fields := make([]string, 0, len(fieldSet))
	for k := range fieldSet {
		fields = append(fields, k)
	}
	sort.Strings(fields)

	for profileName, p := range profiles {
		for _, f := range fields {
			if _, ok := p[f]; !ok {
				return nil, fmt.Errorf("profileOverrides.%s: missing field %q (every profile must set every field)", profileName, f)
			}
		}
	}

	profileNames := make([]string, 0, len(profiles))
	for k := range profiles {
		profileNames = append(profileNames, k)
	}
	sort.Strings(profileNames)

	type fieldOut struct {
		Ident   string // PascalCase Go identifier
		YAMLKey string
	}
	type profileOut struct {
		Ident  string // gen<Profile>Profile, e.g. genDesktopProfile
		Source string // YAML profile name, e.g. "desktop"
		Values map[string]int
	}
	fieldOuts := make([]fieldOut, len(fields))
	for i, f := range fields {
		fieldOuts[i] = fieldOut{Ident: pascal(f), YAMLKey: f}
	}
	profileOuts := make([]profileOut, len(profileNames))
	for i, name := range profileNames {
		profileOuts[i] = profileOut{
			Ident:  "gen" + pascal(name) + "Profile",
			Source: name,
			Values: profiles[name],
		}
	}

	tpl := template.Must(template.New("profiles").Funcs(template.FuncMap{
		"value": func(p profileOut, key string) int { return p.Values[key] },
	}).Parse(profilesTemplate))

	var buf bytes.Buffer
	data := struct {
		Fields   []fieldOut
		Profiles []profileOut
	}{fieldOuts, profileOuts}
	if err := tpl.Execute(&buf, data); err != nil {
		return nil, err
	}
	return format.Source(buf.Bytes())
}

const profilesTemplate = `// Code generated by cmd/gen_design_tokens. DO NOT EDIT.
//
// Source of truth: DESIGN.md ` + "`profileOverrides:`" + ` block.
// Regenerate via: make gen-design-tokens

package ui

// profileValues is the generated container for profile-conditional design
// fields. layout_profile.go's builder functions read these values into
// the larger LayoutProfile struct. Fields here are dimensional / visual-
// style only; runtime feature toggles live in runtime_profile.go.
type profileValues struct {
{{- range .Fields}}
	{{.Ident}} int // profileOverrides.{{.YAMLKey}}
{{- end}}
}

var (
{{- range .Profiles}}
	{{.Ident}} = profileValues{
{{- $p := . -}}
{{range $.Fields}}
		{{.Ident}}: {{value $p .YAMLKey}},
{{- end}}
	}
{{- end}}
)
`
