// Code generated by cmd/gen-chain-spec. DO NOT EDIT.
//
// Source of truth: src/go/internal/audio/chain_spec.go
// Regenerate: cd src/go && go run ./cmd/gen-chain-spec > ../js/chain_spec.gen.js
//
// The post-voice master/mix chain is implemented twice — Go/C on desktop,
// WebAudio nodes in audio.js. These constants keep both configured identically
// so the same instrument sounds the same on both platforms. audio.js reads
// them in ensureCompressor + ensureLimiter; chain_spec_parity.browser.test.js
// asserts the live WebAudio nodes match these values.

// Master compressor. NOTE: audio.js DynamicsCompressorNode takes attack/
// release in SECONDS — divide the *Ms values by 1000.
export const CHAIN_SPEC = Object.freeze({
  compressorThresholdDb: -3,
  compressorRatio: 2.5,
  compressorAttackMs: 5,
  compressorReleaseMs: 80,
  compressorKneeDb: 3,
  softClipThreshold: 0.9,
  voiceHeadroom: 0.18,
  targetSampleRate: 48000,
});
