/**
 * Cross-Platform Parity Browser Test
 *
 * Loads the same JSON fixtures used by the Go parity tests, queries the
 * predictor via visibleAt/audibleAt/triggeredAt JS exports, and compares
 * results against golden files generated by `go test -run TestCrossPlatformParity`.
 *
 * This verifies that the WASM predictor produces bit-identical results
 * to the native Go predictor.
 */

import { setupFullWasm } from "./real_input_test_helpers.js";
import { flushCoverage, isCoverageEnabled } from "./coverage_helpers.js";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const assetsDir = path.resolve(__dirname, "../go/internal/assets");
const goldenDir = path.resolve(__dirname, "../go/internal/ui/testdata");

const HORIZON = 64;

const fixtures = [
  { name: "parity_fixture_simple.json", golden: "parity_golden_simple.json" },
  { name: "parity_fixture_probability.json", golden: "parity_golden_probability.json" },
  { name: "parity_fixture_mute.json", golden: "parity_golden_mute.json" },
  { name: "parity_fixture_multi_row.json", golden: "parity_golden_multi_row.json" },
];

let cleanup;
let page;

try {
  console.log("parity_cross_platform: Setting up WASM...");
  ({ page, cleanup } = await setupFullWasm());

  await page.evaluate(() => forceDraw?.());
  await page.waitForTimeout(200);

  let totalMismatches = 0;

  for (const fixture of fixtures) {
    console.log(`\nparity_cross_platform: Testing ${fixture.name}...`);

    // Load fixture JSON.
    const fixturePath = path.join(assetsDir, fixture.name);
    if (!fs.existsSync(fixturePath)) {
      console.log(`  SKIP: fixture not found at ${fixturePath}`);
      continue;
    }
    const fixtureJSON = fs.readFileSync(fixturePath, "utf-8");

    // Load golden file.
    const goldenPath = path.join(goldenDir, fixture.golden);
    if (!fs.existsSync(goldenPath)) {
      console.log(`  SKIP: golden file not found at ${goldenPath}`);
      console.log("  Run 'go test -run TestCrossPlatformParity' to generate golden files");
      continue;
    }
    const golden = JSON.parse(fs.readFileSync(goldenPath, "utf-8"));

    // Import fixture into WASM.
    await page.evaluate((json) => importJSON?.(json), fixtureJSON);
    await page.waitForTimeout(300);

    // Force update and draw to settle predictor.
    await page.evaluate(() => {
      updateBeatInfosJS?.();
      forceDraw?.();
    });
    await page.waitForTimeout(200);

    // Query predictor for all rows over the horizon.
    const nRows = golden.rows;
    let fixtureMismatches = 0;

    for (let row = 0; row < nRows; row++) {
      const goldenRow = golden.data[row];
      if (!goldenRow) {
        console.log(`  WARNING: golden data missing for row ${row}`);
        continue;
      }

      // Batch-query predictor for efficiency.
      const wasmResult = await page.evaluate(({ row, horizon }) => {
        const visible = [];
        const audible = [];
        const triggered = [];
        for (let idx = 0; idx < horizon; idx++) {
          visible.push(visibleAt?.(row, idx) ?? false);
          audible.push(audibleAt?.(row, idx) ?? false);
          triggered.push(triggeredAt?.(row, idx) ?? false);
        }
        return { visible, audible, triggered };
      }, { row, horizon: HORIZON });

      // Compare against golden.
      let rowMismatches = 0;
      for (let idx = 0; idx < HORIZON; idx++) {
        if (idx < goldenRow.visible.length && wasmResult.visible[idx] !== goldenRow.visible[idx]) {
          if (rowMismatches < 3) {
            console.log(`  MISMATCH row=${row} idx=${idx} visible: wasm=${wasmResult.visible[idx]} golden=${goldenRow.visible[idx]}`);
          }
          rowMismatches++;
        }
        if (idx < goldenRow.audible.length && wasmResult.audible[idx] !== goldenRow.audible[idx]) {
          if (rowMismatches < 3) {
            console.log(`  MISMATCH row=${row} idx=${idx} audible: wasm=${wasmResult.audible[idx]} golden=${goldenRow.audible[idx]}`);
          }
          rowMismatches++;
        }
        if (idx < goldenRow.triggered.length && wasmResult.triggered[idx] !== goldenRow.triggered[idx]) {
          if (rowMismatches < 3) {
            console.log(`  MISMATCH row=${row} idx=${idx} triggered: wasm=${wasmResult.triggered[idx]} golden=${goldenRow.triggered[idx]}`);
          }
          rowMismatches++;
        }
      }

      // Count visible beats for logging.
      const visCount = wasmResult.visible.filter(Boolean).length;
      const audCount = wasmResult.audible.filter(Boolean).length;
      console.log(`  row ${row}: visible=${visCount}/${HORIZON} audible=${audCount}/${HORIZON} mismatches=${rowMismatches}`);
      fixtureMismatches += rowMismatches;
    }

    totalMismatches += fixtureMismatches;
    if (fixtureMismatches === 0) {
      console.log(`  ${fixture.name}: MATCH - WASM predictor matches golden`);
    } else {
      console.log(`  ${fixture.name}: ${fixtureMismatches} mismatches`);
    }
  }

  if (totalMismatches > 0) {
    throw new Error(`Cross-platform parity failed: ${totalMismatches} total mismatches`);
  }

  console.log("\nparity_cross_platform: PASS - All fixtures match golden files");
} catch (error) {
  console.error("parity_cross_platform: FAIL -", error.message);
  process.exitCode = 1;
} finally {
  if (isCoverageEnabled()) await flushCoverage(page, new URL("../../coverage/browser-raw", import.meta.url).pathname, "parity_cross_platform");
  if (cleanup) {
    await cleanup();
  }
}
