// xplat_insert_fx_parity.browser.test.js
//
// Cross-platform insert-effect parity: render the SAME deterministic input
// through every insert effect using the Emscripten build of insert_fx.c
// (drums.single.js — the exact module the production AudioWorklet
// insert_fx_worklet.js instantiates) and diff per-sample against the native
// cgo render locked in src/go/internal/audio/testdata/ifx_xplat_golden.json
// (generated by TestInsertFXXplatGolden).
//
// Native cc may contract a*b+c into FMA on x86 and links glibc libm; wasm has
// no FMA instruction and ships musl-derived libm — so some effects are
// close-but-not-bit-identical by construction. The test therefore reports
// bit-exact per case where it holds and enforces a hard per-sample tolerance
// everywhere (real param-mapping or DSP-drift bugs produce diffs orders of
// magnitude above it).
//
// The effect-init switch below mirrors insert_fx_worklet.js _configure()
// 1:1 — if the worklet's init logic changes, change it here too.
//
// Usage: GO=/path/to/.tools/go/bin/go node src/js/xplat_insert_fx_parity.browser.test.js

import { chromium } from "playwright";
import http from "http";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const jsDir = __dirname;
const repoRoot = path.resolve(jsDir, "..", "..");

const goldenPath = path.join(
  repoRoot,
  "src/go/internal/audio/testdata/ifx_xplat_golden.json",
);
const golden = JSON.parse(fs.readFileSync(goldenPath, "utf-8"));
console.log(
  `Loaded golden: sr=${golden.sample_rate} samples=${golden.samples} chunk=${golden.chunk} effects=${Object.keys(golden.effects).length}`,
);

// Hard per-sample tolerance. Bit-exact cases report as such; anything above
// this is a real divergence (param bug, DSP drift, ABI mismatch).
const MAX_ABS_DIFF = 1e-4;

// Modulated-delay effects with feedback (flanger, chorus) recirculate the
// libm sinf/FMA ULP differences through their feedback path, accumulating to
// ~1e-4 over 8192 samples at feedback 0.8 (≈ -80 dBFS — inaudible, and an
// order of magnitude below any real param-mapping bug). Everything else stays
// at the tight default.
const PER_TYPE_MAX_ABS_DIFF = {
  flanger: 5e-4,
  chorus: 5e-4,
};

const server = http.createServer((req, res) => {
  const file = req.url === "/" ? "/index.html" : req.url;
  const filePath = path.join(jsDir, file.replace(/^\//, ""));
  fs.readFile(filePath, (err, data) => {
    if (err) {
      res.writeHead(404);
      res.end();
      return;
    }
    let ct = "text/plain";
    if (filePath.endsWith(".html")) ct = "text/html";
    else if (filePath.endsWith(".js")) ct = "application/javascript";
    else if (filePath.endsWith(".wasm")) ct = "application/wasm";
    res.writeHead(200, { "Content-Type": ct });
    res.end(data);
  });
});
await new Promise((r) => server.listen(0, r));
const port = server.address().port;

let exitCode = 0;
let browser;
try {
  browser = await chromium.launch();
  const page = await browser.newPage();
  if (process.env.TEST_LOG) {
    page.on("console", (msg) => console.log(`  [page] ${msg.text()}`));
  }
  // Blank page; we only need module scope, not the app.
  await page.goto(`http://localhost:${port}/drums.single.js`, { waitUntil: "commit" });
  await page.setContent("<html><body></body></html>");

  await page.evaluate(async (origin) => {
    const factory = (await import(`${origin}/drums.single.js`)).default;
    window.__ifxMod = await factory({});
  }, `http://localhost:${port}`);

  const results = [];
  for (const [type, cases] of Object.entries(golden.effects)) {
    for (const c of cases) {
      const res = await page.evaluate(
        ({ type, params, pcmB64, sampleRate, samples, chunk }) => {
          const m = window.__ifxMod;
          const sr = sampleRate;
          const p = params;

          // ── init mirror of insert_fx_worklet.js _configure() ──
          let cPtr = 0;
          const auxPtrs = [];
          const alloc = (bytes) => m._malloc(bytes);
          switch (type) {
            case "distortion": {
              cPtr = alloc(64);
              m._ifx_distortion_init(cPtr, sr, p.drive ?? 2, p.tone ?? 4000, p.mix ?? 1);
              break;
            }
            case "delay": {
              cPtr = alloc(128);
              const bufLen = Math.min(sr, Math.max(1, Math.round((p.time ?? 250) * 0.001 * sr + sr * 0.1)));
              const bufPtr = alloc(bufLen * 4);
              auxPtrs.push(bufPtr);
              m._ifx_delay_init(cPtr, sr, bufPtr, bufLen, p.time ?? 250, p.feedback ?? 0.4, p.mix ?? 0.3);
              break;
            }
            case "reverb": {
              cPtr = alloc(256);
              const memSize = m._ifx_reverb_mem_size(sr);
              const memPtr = alloc(memSize * 4);
              auxPtrs.push(memPtr);
              m._ifx_reverb_init(cPtr, sr, memPtr, p.room ?? 0.5, p.damping ?? 0.5, p.mix ?? 0.3);
              break;
            }
            case "chorus": {
              cPtr = alloc(128);
              const depthMs = p.depth ?? 5;
              const bufLen = Math.max(64, Math.round(depthMs * 0.001 * sr * 2) + 64);
              const bufPtr = alloc(bufLen * 4);
              auxPtrs.push(bufPtr);
              m._ifx_chorus_init(cPtr, sr, bufPtr, bufLen, p.rate ?? 1.5, p.depth ?? 5, p.mix ?? 0.5);
              break;
            }
            case "bitcrusher": {
              cPtr = alloc(32);
              m._ifx_bitcrusher_init(cPtr, p.bits ?? 8, p.rate ?? 0.5, p.mix ?? 0.5);
              break;
            }
            case "filter": {
              cPtr = alloc(128);
              m._ifx_filter_init(cPtr, sr, p.mode ?? 0, p.cutoff ?? 1000, p.q ?? 0.707, p.mix ?? 1);
              break;
            }
            case "waveshaper": {
              cPtr = alloc(32);
              m._ifx_waveshaper_init(cPtr, p.curve ?? 0, p.drive ?? 2, p.mix ?? 1);
              break;
            }
            case "ringmod": {
              cPtr = alloc(64);
              m._ifx_ringmod_init(cPtr, sr, p.frequency ?? 440, p.shape ?? 0, p.mix ?? 0.5);
              break;
            }
            case "tremolo": {
              cPtr = alloc(64);
              m._ifx_tremolo_init(cPtr, sr, p.rate ?? 4, p.depth ?? 0.5, p.shape ?? 0, p.mix ?? 1);
              break;
            }
            case "gate": {
              cPtr = alloc(64);
              m._ifx_gate_init(cPtr, sr, p.threshold ?? -30, p.attack ?? 1, p.release ?? 50, p.range ?? -90);
              break;
            }
            case "limiter": {
              cPtr = alloc(64);
              m._ifx_limiter_init(cPtr, sr, p.threshold ?? -1, p.release ?? 50, p.ceiling ?? -0.3);
              break;
            }
            case "flanger": {
              cPtr = alloc(128);
              const depthMs = p.depth ?? 3;
              const bufLen = Math.max(64, Math.round(depthMs * 0.001 * sr * 2) + 64);
              const bufPtr = alloc(bufLen * 4);
              auxPtrs.push(bufPtr);
              m._ifx_flanger_init(cPtr, sr, bufPtr, bufLen, p.rate ?? 0.5, p.depth ?? 3, p.feedback ?? 0.5, p.mix ?? 0.5);
              break;
            }
            case "phaser": {
              cPtr = alloc(256);
              m._ifx_phaser_init(cPtr, sr, p.stages ?? 4, p.rate ?? 0.5, p.depth ?? 0.7, p.feedback ?? 0.5, p.mix ?? 0.5);
              break;
            }
            case "autowah": {
              cPtr = alloc(128);
              m._ifx_autowah_init(cPtr, sr, p.sensitivity ?? 0.5, p.rate ?? 2, p.depth ?? 0.7, p.mix ?? 0.5);
              break;
            }
            case "compressor": {
              cPtr = alloc(128);
              m._ifx_compressor_init(cPtr, sr, p.threshold ?? -20, p.ratio ?? 4, p.attack ?? 10, p.release ?? 100, p.makeup ?? 0, p.mix ?? 1);
              break;
            }
            case "transient": {
              cPtr = alloc(128);
              m._ifx_transient_init(cPtr, sr, p.attack ?? 100, p.sustain ?? 100, p.speed ?? 10);
              break;
            }
            case "tape": {
              cPtr = alloc(128);
              const tBufLen = Math.max(64, Math.round(0.01 * sr) + 64);
              const tBufPtr = alloc(tBufLen * 4);
              auxPtrs.push(tBufPtr);
              m._ifx_tape_init(cPtr, sr, tBufPtr, tBufLen, p.drive ?? 2, p.warmth ?? 0.5, p.wow ?? 0, p.flutter ?? 0, p.mix ?? 1);
              break;
            }
            case "pitchshift": {
              cPtr = alloc(128);
              const psBufLen = Math.max(64, Math.round(0.15 * sr) + 64);
              const psBufPtr = alloc(psBufLen * 4);
              auxPtrs.push(psBufPtr);
              m._ifx_pitchshift_init(cPtr, sr, psBufPtr, psBufLen, p.pitch ?? 0, p.mix ?? 1, p.window ?? 50);
              break;
            }
            default:
              return { error: `unknown effect type ${type}` };
          }

          // ── deterministic input: EXACT mirror of ifxGoldenInput() in
          // ifx_xplat_golden_test.go (integer LCG, f64 divide, f32 round) ──
          const input = new Float32Array(samples);
          let state = 12345;
          for (let i = 0; i < samples; i++) {
            state = (Math.imul(1103515245, state) + 12345) & 0x7fffffff;
            input[i] = Math.fround((state / 2147483647) * 2 - 1);
          }

          const inPtr = alloc(samples * 4);
          const outPtr = alloc(samples * 4);
          new Float32Array(m.HEAPF32.buffer, inPtr, samples).set(input);

          const procName = `_ifx_${type}_process`;
          const proc = m[procName];
          if (!proc) return { error: `missing export ${procName}` };
          for (let off = 0; off < samples; off += chunk) {
            proc(cPtr, inPtr + off * 4, outPtr + off * 4, chunk);
          }
          const out = new Float32Array(samples);
          out.set(new Float32Array(m.HEAPF32.buffer, outPtr, samples));

          // ── decode golden PCM and diff ──
          const bin = atob(pcmB64);
          const bytes = new Uint8Array(bin.length);
          for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
          const want = new Float32Array(bytes.buffer);

          const gotBits = new Uint32Array(out.buffer);
          const wantBits = new Uint32Array(want.buffer);
          let bitExact = true;
          let maxDiff = 0;
          let maxIdx = -1;
          let nonFinite = 0;
          for (let i = 0; i < samples; i++) {
            if (gotBits[i] !== wantBits[i]) bitExact = false;
            if (!Number.isFinite(out[i])) nonFinite++;
            const d = Math.abs(out[i] - want[i]);
            if (d > maxDiff) {
              maxDiff = d;
              maxIdx = i;
            }
          }

          m._free(inPtr);
          m._free(outPtr);
          if (cPtr) m._free(cPtr);
          for (const ptr of auxPtrs) m._free(ptr);

          return { bitExact, maxDiff, maxIdx, nonFinite };
        },
        {
          type,
          params: c.params,
          pcmB64: c.pcm_f32le_b64,
          sampleRate: golden.sample_rate,
          samples: golden.samples,
          chunk: golden.chunk,
        },
      );

      if (res.error) {
        console.error(`✗ ${type}/${c.name}: ${res.error}`);
        exitCode = 1;
        continue;
      }
      const tol = PER_TYPE_MAX_ABS_DIFF[type] ?? MAX_ABS_DIFF;
      const ok = res.nonFinite === 0 && res.maxDiff <= tol;
      const grade = res.bitExact ? "bit-exact" : `maxDiff=${res.maxDiff.toExponential(2)}@${res.maxIdx}`;
      results.push({ type, caseName: c.name, ...res });
      if (!ok) {
        console.error(
          `✗ ${type}/${c.name}: ${grade} nonFinite=${res.nonFinite} exceeds tolerance ${tol}`,
        );
        exitCode = 1;
      } else {
        console.log(`✓ ${type}/${c.name}: ${grade}`);
      }
    }
  }

  const exact = results.filter((r) => r.bitExact).length;
  console.log(
    `\n[ifx-xplat] ${results.length} cases: ${exact} bit-exact, ${results.length - exact} tolerance-grade (≤${MAX_ABS_DIFF}), failures=${exitCode ? "yes" : "none"}`,
  );
} catch (err) {
  console.error("FATAL:", err);
  exitCode = 1;
} finally {
  if (browser) await browser.close();
  server.close();
}
process.exit(exitCode);
