// Code generated by cmd/gen_design_tokens from DESIGN.md instrumentSequence:. DO NOT EDIT.

package templates

// InstrumentSequence is the canonical, ordered, finite instrument color series
// (opaque #RRGGBBAA hex) shared with internal/ui (genInstrumentSequence). Genre
// templates assign row N the color InstrumentSequence[N % len], so every
// circuit's instrument colors are derived from one predictable series. There
// are no hand-maintained hex lists — edit DESIGN.md instrumentSequence: and
// re-run `make gen-design-tokens`.
var InstrumentSequence = []string{
	"#EE00DDFF", // hot-pink-400
	"#00C8E0FF", // cyan-300
	"#FFD319FF", // sunset-gold-200
	"#A030FFFF", // orchid-300
	"#3FD67AFF", // mint-300
	"#3A6AF0FF", // electric-blue-300
	"#FF7A3DFF", // tangerine-300
	"#FF6AD5FF", // hot-pink-200
}
