//go:build !test && !js

// gen-synth-abi emits src/js/synth_param_abi.gen.js from the canonical
// synthParamSchema declared in internal/audio. Drives the JS bridge's
// schema-keyed write loop so audio.js no longer has a hand-maintained
// positional list of heap[0..N] indices that must match the C struct
// layout.
//
// Usage:
//
//	cd src/go && go run ./cmd/gen-synth-abi > ../js/synth_param_abi.gen.js
//
// A drift test (synth_param_schema_test.go) regenerates and diffs so
// commits cannot land with a stale gen file.
package main

import (
	"bytes"
	"fmt"
	"math"
	"os"
	"strings"

	"github.com/ingyamilmolinar/beatmo/internal/audio"
)

func main() {
	var buf bytes.Buffer
	schema := audio.SynthParamSchema()
	identity := audio.SynthParamSchemaIdentity()

	buf.WriteString("// Code generated by cmd/gen-synth-abi. DO NOT EDIT.\n")
	buf.WriteString("//\n")
	buf.WriteString("// Source of truth: src/go/internal/audio/synth_param_schema.go\n")
	buf.WriteString("// Regenerate: cd src/go && go run ./cmd/gen-synth-abi > ../js/synth_param_abi.gen.js\n")
	buf.WriteString("\n")
	buf.WriteString("// SYNTH_PARAM_COUNT is the number of float fields in the C synth_params\n")
	buf.WriteString("// struct (src/c/synth_params.h). audio.js uses it to size the malloc.\n")
	fmt.Fprintf(&buf, "export const SYNTH_PARAM_COUNT = %d;\n\n", len(schema))

	buf.WriteString("// SYNTH_PARAM_INDEX maps a canonical knob name to its struct-member index.\n")
	buf.WriteString("// audio.js writes heap[SYNTH_PARAM_INDEX[name]] = value instead of using a\n")
	buf.WriteString("// hand-maintained positional list. Adding/reordering fields in the C\n")
	buf.WriteString("// struct requires regenerating this file.\n")
	buf.WriteString("export const SYNTH_PARAM_INDEX = Object.freeze({\n")
	for i, name := range schema {
		fmt.Fprintf(&buf, "  %s: %d,\n", jsKey(name), i)
	}
	buf.WriteString("});\n\n")

	buf.WriteString("// SYNTH_PARAM_IDENTITY is the no-op default for each knob. Used when the\n")
	buf.WriteString("// caller's params object does not declare a value, so unset knobs do not\n")
	buf.WriteString("// alter the rendered sound. Values mirror the C sp_* accessor fallbacks\n")
	buf.WriteString("// in src/c/synth_params.h.\n")
	buf.WriteString("export const SYNTH_PARAM_IDENTITY = Object.freeze({\n")
	for _, name := range schema {
		v, ok := identity[name]
		if !ok {
			fmt.Fprintf(os.Stderr, "gen-synth-abi: missing identity for %q (update SynthParamSchemaIdentity)\n", name)
			os.Exit(1)
		}
		fmt.Fprintf(&buf, "  %s: %s,\n", jsKey(name), formatFloat(v))
	}
	buf.WriteString("});\n")

	// ── Modular voice block ──────────────────────────────────────────────────
	modSchema := audio.ModularParamSchema()
	modIdentity := audio.ModularParamSchemaIdentity()

	buf.WriteString("\n")
	buf.WriteString("// MODULAR_PARAM_COUNT is the number of float fields in the C modular_params\n")
	buf.WriteString("// struct (src/c/modular.h) — the unified modular synth voice's wide param\n")
	buf.WriteString("// block, distinct from the 7-field synth_params above. audio.js selects this\n")
	buf.WriteString("// block (size + index + identity) for instruments flagged paramBlock:'modular'.\n")
	fmt.Fprintf(&buf, "export const MODULAR_PARAM_COUNT = %d;\n\n", len(modSchema))

	buf.WriteString("// MODULAR_PARAM_INDEX maps a modular knob name to its struct-member index.\n")
	buf.WriteString("export const MODULAR_PARAM_INDEX = Object.freeze({\n")
	for i, name := range modSchema {
		fmt.Fprintf(&buf, "  %s: %d,\n", jsKey(name), i)
	}
	buf.WriteString("});\n\n")

	buf.WriteString("// MODULAR_PARAM_IDENTITY is the fill value for each modular knob when the\n")
	buf.WriteString("// caller omits it. Unlike the post-process synth block these are the voice's\n")
	buf.WriteString("// built-in DEFAULTS (they define the sound) and mirror the mp_get fallbacks in\n")
	buf.WriteString("// src/c/modular.c and the ModularSynthParamDefs defaults.\n")
	buf.WriteString("export const MODULAR_PARAM_IDENTITY = Object.freeze({\n")
	for _, name := range modSchema {
		v, ok := modIdentity[name]
		if !ok {
			fmt.Fprintf(os.Stderr, "gen-synth-abi: missing modular identity for %q (update ModularParamSchemaIdentity)\n", name)
			os.Exit(1)
		}
		fmt.Fprintf(&buf, "  %s: %s,\n", jsKey(name), formatFloat(v))
	}
	buf.WriteString("});\n")

	// ── Family blocks (native-deprecation migration) ─────────────────────────
	// EVERY native engine family migrated to the modular engine — no family param
	// block remains. All migrated families' knobs travel in the modular block
	// (paramBlock:'modular'); the modular block above covers them.
	// FM block removed — the FM family migrated to the modular engine (Phase-7,
	// the LAST legacy family); its knobs travel in the modular_params block
	// (gen_fm_* columns), not an fm block.
	// CYMBAL block removed — the cymbal family migrated to the modular engine
	// (Phase-6); its knobs travel in the modular_params block, not a cymbal block.
	// BASS block removed — the bass family migrated to the modular engine
	// (Phase-2); its knobs travel in the modular_params block, not a bass block.
	// KICK block removed — the kick family migrated to the modular engine
	// (Phase-3); its knobs travel in the modular_params block, not a kick block.
	// TOM block removed — the tom family migrated to the modular engine
	// (Phase-4); its knobs travel in the modular_params block, not a tom block.
	// SNARE block removed — the snare family migrated to the modular engine
	// (Phase-5); its knobs travel in the modular_params block, not a snare block.

	if _, err := os.Stdout.Write(buf.Bytes()); err != nil {
		fmt.Fprintf(os.Stderr, "gen-synth-abi: write failed: %v\n", err)
		os.Exit(1)
	}
}

// emitFamilyBlock writes one family param block (COUNT + INDEX + IDENTITY)
// in the same shape as the modular block. audio.js selects a family block
// for instruments flagged paramBlock:'<family>' (lowercased prefix).
func emitFamilyBlock(buf *bytes.Buffer, prefix, cRef string, schema []string, identity map[string]float64) {
	buf.WriteString("\n")
	fmt.Fprintf(buf, "// %s_PARAM_COUNT is the number of float fields in the C struct (%s).\n", prefix, cRef)
	fmt.Fprintf(buf, "// Indices 0..6 are the embedded synth_params base; family fields follow.\n")
	fmt.Fprintf(buf, "export const %s_PARAM_COUNT = %d;\n\n", prefix, len(schema))

	fmt.Fprintf(buf, "// %s_PARAM_INDEX maps a knob name to its struct-member index.\n", prefix)
	fmt.Fprintf(buf, "export const %s_PARAM_INDEX = Object.freeze({\n", prefix)
	for i, name := range schema {
		fmt.Fprintf(buf, "  %s: %d,\n", jsKey(name), i)
	}
	buf.WriteString("});\n\n")

	fmt.Fprintf(buf, "// %s_PARAM_IDENTITY is the fill value for each knob when the caller omits\n", prefix)
	fmt.Fprintf(buf, "// it. Base knobs use their no-op identities; family fields use NaN — the\n")
	fmt.Fprintf(buf, "// \"unset\" sentinel telling the C engine to keep its hardcoded literal.\n")
	fmt.Fprintf(buf, "export const %s_PARAM_IDENTITY = Object.freeze({\n", prefix)
	for _, name := range schema {
		v, ok := identity[name]
		if !ok {
			fmt.Fprintf(os.Stderr, "gen-synth-abi: missing %s identity for %q (update the schema identity map)\n", prefix, name)
			os.Exit(1)
		}
		fmt.Fprintf(buf, "  %s: %s,\n", jsKey(name), formatFloat(v))
	}
	buf.WriteString("});\n")
}

// jsKey returns name quoted only if necessary so the output stays readable
// (e.g. "pitch" appears as `pitch:` not `"pitch":`).
func jsKey(name string) string {
	if isIdent(name) {
		return name
	}
	return `"` + strings.ReplaceAll(name, `"`, `\"`) + `"`
}

func isIdent(s string) bool {
	if s == "" {
		return false
	}
	for i, r := range s {
		ok := (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || r == '_' || r == '$'
		if i > 0 {
			ok = ok || (r >= '0' && r <= '9')
		}
		if !ok {
			return false
		}
	}
	return true
}

// formatFloat returns a JS-friendly representation of v. Integers render
// without trailing decimals so the gen file diff stays small. NaN renders as
// the JS global NaN (the family blocks' "unset" sentinel).
func formatFloat(v float64) string {
	if math.IsNaN(v) {
		return "NaN"
	}
	if v == float64(int64(v)) {
		return fmt.Sprintf("%d", int64(v))
	}
	return fmt.Sprintf("%g", v)
}
