package assets

import (
	"embed"
	"encoding/json"
	"strings"
)

//go:embed templates/*.json
var templateFS embed.FS

// Template is a built-in genre circuit: display metadata + the importable JSON.
//
// All 15 templates recreate the instrumental signature of one genre-defining
// masterpiece each (see docs/superpowers/specs/2026-06-20-genre-masterpiece-templates-design.md).
// They are GENERATED by cmd/gen-showcase from the pattern-card specs in
// cmd/gen-showcase/specs.go — never hand-edit templates/*.json.
//
//	Regenerate via: cd src/go && ../../.tools/go/bin/go run ./cmd/gen-showcase
//	A drift test (cmd/gen-showcase/drift_test.go) ensures committed JSON matches specs.
//
// Display name and BPM are derived from each file, so the only metadata kept in
// Go is the menu order.
type Template struct {
	Genre   string
	Display string
	BPM     int
	Bytes   []byte
}

// templateOrder is the canonical menu order, by file stem (templates/<stem>.json).
// It is the ONLY hand-maintained template metadata; Display and BPM are derived
// from the embedded JSON so they cannot drift from what actually ships.
var templateOrder = []string{
	// Classical (Baroque → Classical era).
	"bach-toccata", "vivaldi-spring", "mozart-k545", "bach-prelude-c", "bach-flute-allemande", "asturias",
	"bach-cello-prelude", "pachelbel-violin", "marcello-oboe", "cielito-trumpet", "handel-water-horn",
	"felt-prelude", "sax-blues", "steel-folk", "electric-riff", "clav-funk", "bass-groove", "conga-tumbao",
	// Bossa · Jazz · Blues.
	"jobim-ipanema", "miles-so-what", "bbking-thrill-is-gone",
	// Funk · Disco.
	"wonder-superstition", "chic-good-times",
	// Rock · Reggae · Pop.
	"eagles-hotel-california", "marley-exodus", "toto-africa",
	// Hip-Hop · House · Techno.
	"dre-g-thang", "blackbox-ride-on-time", "gaynor-survive",
	// Salsa · Bachata.
	"puente-oye-como-va", "salsa-vivir", "bachata-obsesion",
}

// Templates returns the built-in genre circuits in menu order. Panics at init
// only if an embedded file is missing or malformed — a build-time guarantee,
// never runtime (the embed + the JSON shape are both compile/test enforced).
func Templates() []Template {
	out := make([]Template, 0, len(templateOrder))
	for _, genre := range templateOrder {
		b, err := templateFS.ReadFile("templates/" + genre + ".json")
		if err != nil {
			panic("assets: missing embedded template " + genre + ".json: " + err.Error())
		}
		var meta struct {
			BPM int `json:"bpm"`
		}
		if err := json.Unmarshal(b, &meta); err != nil {
			panic("assets: malformed template " + genre + ".json: " + err.Error())
		}
		out = append(out, Template{
			Genre:   genre,
			Display: displayName(genre),
			BPM:     meta.BPM,
			Bytes:   b,
		})
	}
	return out
}

// displayTitles maps each template stem to its real "Artist — Song" menu title.
// The whole point of the slate is A/B-ing each template against the named
// original, so the menu must show the song — not a title-cased stem (which would
// render "Dre-G-Thang", "Bbking-Thrill-Is-Gone", …). Every stem in templateOrder
// must have an entry here; TestTemplates_DisplayNamed enforces it.
var displayTitles = map[string]string{
	"bach-toccata":            "Bach — Toccata & Fugue in D minor",
	"vivaldi-spring":          "Vivaldi — Spring",
	"mozart-k545":             "Mozart — Sonata K545",
	"bach-prelude-c":          "Bach — Prelude in C (BWV 846)",
	"bach-flute-allemande":    "Bach — Flute Partita Allemande (BWV 1013)",
	"asturias":                "Albéniz — Asturias (Leyenda)",
	"bach-cello-prelude":      "Bach — Cello Suite 1 Prelude (BWV 1007)",
	"pachelbel-violin":        "Pachelbel — Canon in D — Violin",
	"marcello-oboe":           "Marcello — Oboe Concerto in D minor, Adagio",
	"cielito-trumpet":         "Cielito Lindo (Mendoza, 1882) — Mariachi Trumpet",
	"handel-water-horn":       "Handel — Water Music, Bourrée — French Horn",
	"felt-prelude":            "Felt Piano — Bach Prelude (soft)",
	"sax-blues":               "Blues Line — Alto Sax",
	"steel-folk":              "Folk Fingerpick — Steel Guitar",
	"electric-riff":           "Pentatonic Riff — Electric Guitar",
	"clav-funk":               "Funk Riff — Guitar",
	"bass-groove":             "Bass Groove — Synth Bass",
	"conga-tumbao":            "Tumbao — Congas",
	"jobim-ipanema":           "Jobim — The Girl from Ipanema",
	"miles-so-what":           "Miles Davis — So What",
	"bbking-thrill-is-gone":   "B.B. King — The Thrill Is Gone",
	"wonder-superstition":     "Stevie Wonder — Superstition",
	"chic-good-times":         "Chic — Good Times",
	"eagles-hotel-california": "Eagles — Hotel California",
	"marley-exodus":           "Bob Marley — Exodus",
	"toto-africa":             "Toto — Africa",
	"dre-g-thang":             "Dr. Dre — Nuthin' but a 'G' Thang",
	"blackbox-ride-on-time":   "Black Box — Ride On Time",
	"gaynor-survive":          "Gloria Gaynor — I Will Survive",
	"puente-oye-como-va":      "Tito Puente — Oye Como Va",
	"salsa-vivir":             "Salsa — Vivir Mi Vida",
	"bachata-obsesion":        "Bachata — Obsesión",
}

// displayName returns the menu title for a stem: the curated song title when
// known, otherwise a title-cased fallback ("hip-hop" -> "Hip-Hop") so an
// unmapped stem still renders a sane label rather than panicking.
func displayName(genre string) string {
	if title, ok := displayTitles[genre]; ok {
		return title
	}
	parts := strings.Split(genre, "-")
	for i, p := range parts {
		if p == "" {
			continue
		}
		parts[i] = strings.ToUpper(p[:1]) + p[1:]
	}
	return strings.Join(parts, "-")
}
